import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cors={ 'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type' };
const schema={type:'object',additionalProperties:false,required:['statement_from','statement_to','opening_balance','closing_balance','currency','rows'],properties:{statement_from:{type:['string','null']},statement_to:{type:['string','null']},opening_balance:{type:['number','null']},closing_balance:{type:['number','null']},currency:{type:'string'},rows:{type:'array',items:{type:'object',additionalProperties:false,required:['source_page','source_line','booked_date','value_date','description','counterparty','reference','amount','currency','confidence'],properties:{source_page:{type:['integer','null']},source_line:{type:['string','null']},booked_date:{type:['string','null']},value_date:{type:['string','null']},description:{type:['string','null']},counterparty:{type:['string','null']},reference:{type:['string','null']},amount:{type:['number','null']},currency:{type:['string','null']},confidence:{type:'number'}}}}}};

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,key=Deno.env.get('OPENAI_API_KEY');
 if(!key)throw new Error('OPENAI_API_KEY is not configured');const token=req.headers.get('Authorization')||'';const isService=token===`Bearer ${service}`;const userClient=createClient(url,anon,{global:{headers:{Authorization:token}}});const{data:{user}}=isService?{data:{user:null}}:await userClient.auth.getUser();if(!isService&&!user)throw new Error('Unauthorized');
 const{import_id}=await req.json();const admin=createClient(url,service);const{data:record,error:recordError}=await admin.from('bank_statement_imports').select('*').eq('id',import_id).single();if(recordError)throw recordError;if(!isService){const{data:membership}=await admin.from('workspace_members').select('role').eq('workspace_id',record.workspace_id).eq('user_id',user!.id).maybeSingle();if(!membership||!['owner','admin','writer','accountant'].includes(membership.role))throw new Error('Not authorized');}if(record.status==='imported')throw new Error('Imported statements cannot be re-extracted');
 const{data:file,error:fileError}=await admin.storage.from('finance-documents').download(record.file_path);if(fileError)throw fileError;const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const base64=btoa(binary);
 const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.4-nano',store:false,input:[{role:'user',content:[{type:'input_file',filename:record.file_name,file_data:`data:application/pdf;base64,${base64}`},{type:'input_text',text:'Extract this bank or credit-card statement exactly. Amounts must be signed from the account perspective: money in positive, money out negative. Preserve source text and page. Never infer missing dates or amounts; use null. Return every transaction row once.'}]}],text:{format:{type:'json_schema',name:'bank_statement',strict:true,schema}}})});
 if(!response.ok)throw new Error(`OpenAI extraction failed: ${await response.text()}`);const result=await response.json();const output=result.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text;if(!output)throw new Error('No structured extraction returned');const parsed=JSON.parse(output);
 await admin.from('bank_statement_rows').delete().eq('statement_import_id',import_id);if(parsed.rows.length){const{error:rowsError}=await admin.from('bank_statement_rows').insert(parsed.rows.map((r:any,i:number)=>({...r,statement_import_id:import_id,workspace_id:record.workspace_id,row_order:i+1,review_status:'proposed',classification:'unknown'})));if(rowsError)throw rowsError;}
 await admin.from('bank_statement_imports').update({statement_from:parsed.statement_from,statement_to:parsed.statement_to,opening_balance:parsed.opening_balance,closing_balance:parsed.closing_balance,currency:parsed.currency||record.currency,status:'needs_review',extraction_method:'ocr_ai',extraction_error:null,extraction_model:'gpt-5.4-nano',extraction_response_id:result.id,extracted_row_count:parsed.rows.length,extracted_at:new Date().toISOString()}).eq('id',import_id);
 return new Response(JSON.stringify({rows:parsed.rows.length}),{headers:{...cors,'Content-Type':'application/json'}});
}catch(error){return new Response(JSON.stringify({error:error instanceof Error?error.message:String(error)}),{status:400,headers:{...cors,'Content-Type':'application/json'}})}});
