import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { PDFDocument } from 'https://esm.sh/pdf-lib@1.17.1';

const cors={ 'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type' };
const schema={type:'object',additionalProperties:false,required:['statement_from','statement_to','opening_balance','closing_balance','total_debits','total_credits','currency','rows'],properties:{statement_from:{type:'string'},statement_to:{type:'string'},opening_balance:{type:'number'},closing_balance:{type:'number'},total_debits:{type:'number'},total_credits:{type:'number'},currency:{type:'string'},rows:{type:'array',items:{type:'object',additionalProperties:false,required:['source_page','source_line','booked_date','value_date','description','counterparty','reference','amount','currency','confidence'],properties:{source_page:{type:'integer'},source_line:{type:'string'},booked_date:{type:'string'},value_date:{type:['string','null']},description:{type:'string'},counterparty:{type:['string','null']},reference:{type:['string','null']},amount:{type:'number'},currency:{type:'string'},confidence:{type:'number'}}}}}};

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,key=Deno.env.get('OPENAI_API_KEY');
 if(!key)throw new Error('OPENAI_API_KEY is not configured');const token=req.headers.get('Authorization')||'';let tokenRole='';try{tokenRole=JSON.parse(atob(token.replace(/^Bearer /,'').split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role||''}catch{/* non-JWT tokens use normal user authentication */}const isService=tokenRole==='service_role'||token===`Bearer ${service}`;const userClient=createClient(url,anon,{global:{headers:{Authorization:token}}});const{data:{user}}=isService?{data:{user:null}}:await userClient.auth.getUser();if(!isService&&!user)throw new Error('Unauthorized');
 const{import_id,page_from,page_to}=await req.json();const admin=createClient(url,service);const{data:record,error:recordError}=await admin.from('bank_statement_imports').select('*').eq('id',import_id).single();if(recordError)throw recordError;if(!isService){const{data:membership}=await admin.from('workspace_members').select('role').eq('workspace_id',record.workspace_id).eq('user_id',user!.id).maybeSingle();if(!membership||!['owner','admin','writer','accountant'].includes(membership.role))throw new Error('Not authorized');}if(record.status==='imported')throw new Error('Imported statements cannot be re-extracted');
 const{data:file,error:fileError}=await admin.storage.from('finance-documents').download(record.file_path);if(fileError)throw fileError;let bytes=new Uint8Array(await file.arrayBuffer());let pageOffset=0;if(page_from||page_to){const source=await PDFDocument.load(bytes);const first=Number(page_from||1),last=Number(page_to||source.getPageCount());if(first<1||last<first||last>source.getPageCount())throw new Error('Invalid PDF page range');pageOffset=first-1;const subset=await PDFDocument.create();const pages=await subset.copyPages(source,Array.from({length:last-first+1},(_,i)=>first-1+i));pages.forEach(p=>subset.addPage(p));bytes=await subset.save();}let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const base64=btoa(binary);
 const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.4',store:false,input:[{role:'user',content:[{type:'input_file',filename:record.file_name,file_data:`data:application/pdf;base64,${base64}`},{type:'input_text',text:'Extract one Bank Austria account statement. Use ONLY the consecutive summary pages headed TERMINAUSZUG with Auszug/Blatt; ignore the cover page and every later individual voucher/detail page. A transaction can continue onto the next summary page: join it once. Dates must be ISO YYYY-MM-DD using the statement year. Amounts with a trailing minus sign are negative; credits are positive. total_debits is the positive printed Summe der Belastungen and total_credits is the positive printed Summe der Gutschriften. Preserve exact source text and source PDF page. Return every summary transaction exactly once. Before responding, verify: sum of negative rows equals -total_debits, sum of positive rows equals total_credits, and opening balance plus all signed rows equals closing balance.'}]}],text:{format:{type:'json_schema',name:'bank_statement',strict:true,schema}}})});
 if(!response.ok)throw new Error(`OpenAI extraction failed: ${await response.text()}`);const result=await response.json();const output=result.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text;if(!output)throw new Error('No structured extraction returned');const parsed=JSON.parse(output);const invalid=parsed.rows.some((r:any)=>!/^\d{4}-\d{2}-\d{2}$/.test(r.booked_date)||!Number.isFinite(r.amount));const debits=-parsed.rows.filter((r:any)=>r.amount<0).reduce((s:number,r:any)=>s+r.amount,0);const credits=parsed.rows.filter((r:any)=>r.amount>0).reduce((s:number,r:any)=>s+r.amount,0);const movement=credits-debits;if(invalid||Math.abs(debits-parsed.total_debits)>.01||Math.abs(credits-parsed.total_credits)>.01||Math.abs(parsed.opening_balance+movement-parsed.closing_balance)>.01)throw new Error(`Extraction failed controls: invalid=${invalid}, debits=${debits}, credits=${credits}, movement=${movement}`);
 await admin.from('bank_statement_rows').delete().eq('statement_import_id',import_id);if(parsed.rows.length){const{error:rowsError}=await admin.from('bank_statement_rows').insert(parsed.rows.map((r:any,i:number)=>({...r,source_page:r.source_page+pageOffset,statement_import_id:import_id,workspace_id:record.workspace_id,row_order:i+1,review_status:'proposed',classification:'unknown'})));if(rowsError)throw rowsError;}
 await admin.from('bank_statement_imports').update({statement_from:parsed.statement_from,statement_to:parsed.statement_to,opening_balance:parsed.opening_balance,closing_balance:parsed.closing_balance,currency:parsed.currency||record.currency,status:'needs_review',extraction_method:'ocr_ai',extraction_error:null,extraction_model:'gpt-5.4',extraction_response_id:result.id,extracted_row_count:parsed.rows.length,extracted_at:new Date().toISOString()}).eq('id',import_id);
 return new Response(JSON.stringify({rows:parsed.rows.length}),{headers:{...cors,'Content-Type':'application/json'}});
}catch(error){const message=error instanceof Error?error.message:typeof error==='object'?JSON.stringify(error):String(error);return new Response(JSON.stringify({error:message}),{status:400,headers:{...cors,'Content-Type':'application/json'}})}});
