import { FormEvent, useEffect, useState } from 'react';
import { Pencil, Plus } from 'lucide-react';
import { useApp } from '../contexts/AppContext';
import { supabase } from '../lib/supabase';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { Modal } from '../components/Modal';

type Bank={id:string;account_name:string;bank_name:string;currency:string;iban:string|null;bic_swift:string|null;account_number:string|null;routing_details:string|null;is_default:boolean};
const blank=(currency='')=>({account_name:'',bank_name:'',currency,iban:'',bic_swift:'',account_number:'',routing_details:'',is_default:true});

export function CompanyBanks(){
  const{workspaceId,workspace}=useApp();
  const[rows,setRows]=useState<Bank[]>([]);
  const[open,setOpen]=useState(false);
  const[editingId,setEditingId]=useState<string|null>(null);
  const[msg,setMsg]=useState('');
  const[form,setForm]=useState(blank());

  const load=async()=>{if(!workspaceId)return;const{data,error}=await supabase.from('company_bank_accounts').select('*').eq('workspace_id',workspaceId).eq('is_active',true).order('is_default',{ascending:false});if(error)setMsg(error.message);else setRows((data||[])as Bank[])};
  useEffect(()=>{setForm(blank(workspace?.base_currency||''));setEditingId(null);setOpen(false);void load()},[workspaceId,workspace?.base_currency]);
  const close=()=>{setOpen(false);setEditingId(null);setForm(blank(workspace?.base_currency||''))};
  const add=()=>{setEditingId(null);setForm(blank(workspace?.base_currency||''));setMsg('');setOpen(true)};
  const edit=(bank:Bank)=>{setEditingId(bank.id);setForm({account_name:bank.account_name,bank_name:bank.bank_name,currency:bank.currency,iban:bank.iban||'',bic_swift:bank.bic_swift||'',account_number:bank.account_number||'',routing_details:bank.routing_details||'',is_default:bank.is_default});setMsg('');setOpen(true)};
  const save=async(event:FormEvent)=>{event.preventDefault();if(!workspaceId)return;setMsg('Saving…');if(form.is_default){const reset=await supabase.from('company_bank_accounts').update({is_default:false}).eq('workspace_id',workspaceId);if(reset.error)return setMsg(reset.error.message)}const payload={...form,workspace_id:workspaceId,iban:form.iban.trim()||null,bic_swift:form.bic_swift.trim()||null,account_number:form.account_number.trim()||null,routing_details:form.routing_details.trim()||null,updated_at:new Date().toISOString()};const result=editingId?await supabase.from('company_bank_accounts').update(payload).eq('id',editingId).eq('workspace_id',workspaceId).select('id').single():await supabase.from('company_bank_accounts').insert(payload).select('id').single();if(result.error)return setMsg(result.error.message);close();setMsg('Bank details saved.');void load()};

  return <div><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-3xl font-bold">Company bank details</h1><p className="text-gray-600 mt-1">Payment instructions snapshotted onto issued invoices.</p></div><Button onClick={add}><Plus className="w-4 h-4 mr-2"/>Add bank account</Button></div>{msg&&<p className="bg-amber-50 p-3 rounded mb-4">{msg}</p>}<div className="grid md:grid-cols-2 gap-4">{rows.map(bank=><div key={bank.id} className="bg-white border rounded-xl p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{bank.account_name}</p>{bank.is_default&&<span className="mt-1 inline-block text-xs bg-blue-50 text-blue-700 px-2 py-1 rounded">Default</span>}</div><Button size="sm" variant="secondary" onClick={()=>edit(bank)}><Pencil className="mr-1 h-4 w-4"/>Edit</Button></div><p className="text-sm text-gray-500 mt-2">{bank.bank_name} · {bank.currency}</p><p className="text-sm mt-4">{bank.iban||bank.account_number||'No account identifier'}</p><p className="text-xs text-gray-500">{bank.bic_swift||''}</p>{bank.routing_details&&<p className="mt-2 whitespace-pre-line text-xs text-gray-500">{bank.routing_details}</p>}</div>)}</div><Modal isOpen={open} onClose={close} title={editingId?'Edit company bank account':'Add company bank account'}><form onSubmit={save} className="space-y-3"><Input required label="Account holder" value={form.account_name} onChange={event=>setForm({...form,account_name:event.target.value})}/><Input required label="Bank name" value={form.bank_name} onChange={event=>setForm({...form,bank_name:event.target.value})}/><Input required label="Currency" value={form.currency} onChange={event=>setForm({...form,currency:event.target.value.toUpperCase()})}/><Input label="IBAN" value={form.iban} onChange={event=>setForm({...form,iban:event.target.value})}/><Input label="BIC / SWIFT" value={form.bic_swift} onChange={event=>setForm({...form,bic_swift:event.target.value})}/><Input label="Account number (non-IBAN)" value={form.account_number} onChange={event=>setForm({...form,account_number:event.target.value})}/><div><label className="mb-1 block text-sm font-medium text-gray-700">Routing details</label><textarea rows={3} value={form.routing_details} onChange={event=>setForm({...form,routing_details:event.target.value})} className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500"/></div><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.is_default} onChange={event=>setForm({...form,is_default:event.target.checked})}/>Default for documents</label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit">{editingId?'Update bank details':'Save bank details'}</Button></div></form></Modal></div>;
}
