import { FormEvent, useEffect, useState } from 'react';
import { useApp } from '../contexts/AppContext';
import { supabase } from '../lib/supabase';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { Select } from '../components/Select';

type Kind='invoice'|'quote'|'credit_note';
type Template={id:string;name:string;language_code:string;is_default:boolean;font_family:string;accent_color:string;footer_text:string;payment_instructions:string;payment_instructions_font_size:string;logo_path:string};
const empty:Template={id:'',name:'',language_code:'en',is_default:false,font_family:'helvetica',accent_color:'#2563eb',footer_text:'',payment_instructions:'',payment_instructions_font_size:'9',logo_path:''};

export function DocumentTemplates(){
  const{workspaceId,workspace}=useApp();const[kind,setKind]=useState<Kind>('invoice');const[templates,setTemplates]=useState<Template[]>([]);const[form,setForm]=useState<Template>(empty);const[logoUrl,setLogoUrl]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
  const apply=async(data:Record<string,unknown>|null)=>{const value=data?{...empty,...data,payment_instructions:String(data.payment_instructions||''),footer_text:String(data.footer_text||''),payment_instructions_font_size:String(data.payment_instructions_font_size||9),logo_path:String(data.logo_path||'')}:empty;setForm(value as Template);if(value.logo_path){const{data:signed}=await supabase.storage.from('finance-documents').createSignedUrl(String(value.logo_path),3600);setLogoUrl(signed?.signedUrl||'')}else setLogoUrl('')};
  const load=async(preferred?:string)=>{if(!workspaceId)return;const{data,error}=await supabase.from('document_templates').select('*').eq('workspace_id',workspaceId).eq('document_type',kind).order('name');if(error)return setMsg(error.message);const rows=(data||[])as unknown as Template[];setTemplates(rows);await apply(rows.find(x=>x.id===preferred)||rows.find(x=>x.is_default)||rows[0]||null)};
  useEffect(()=>{setMsg('');void load()},[workspaceId,kind]);
  const payload=(logoPath=form.logo_path)=>({workspace_id:workspaceId,document_type:kind,name:form.name.trim(),language_code:form.language_code,is_default:form.is_default,font_family:form.font_family,accent_color:form.accent_color,footer_text:form.footer_text.trim()||null,payment_instructions:form.payment_instructions.trim()||null,payment_instructions_font_size:Number(form.payment_instructions_font_size),logo_path:logoPath||null,updated_at:new Date().toISOString()});
  const save=async(event:FormEvent)=>{event.preventDefault();if(!workspaceId||!form.name.trim())return setMsg('Give this layout a name.');setBusy(true);setMsg('Saving…');if(form.is_default)await supabase.from('document_templates').update({is_default:false}).eq('workspace_id',workspaceId).eq('document_type',kind);const result=form.id?await supabase.from('document_templates').update(payload()).eq('id',form.id).select('*').single():await supabase.from('document_templates').insert(payload()).select('*').single();setBusy(false);if(result.error||!result.data)return setMsg(result.error?.message||'The layout was not saved.');await load(result.data.id);setMsg('Document layout saved and verified.')};
  const upload=async(file:File)=>{if(!workspaceId)return;setBusy(true);setMsg('Uploading logo…');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${workspaceId}/document-assets/${kind}-${Date.now()}-${safe}`;const uploaded=await supabase.storage.from('finance-documents').upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error){setBusy(false);return setMsg(uploaded.error.message)}setForm({...form,logo_path:path});setLogoUrl(URL.createObjectURL(file));setBusy(false);setMsg('Logo ready. Save the layout to keep it.')};
  const remove=async()=>{if(!form.id||!confirm(`Delete layout “${form.name}”? Existing documents using it will fall back to the default layout.`))return;const{error}=await supabase.from('document_templates').delete().eq('id',form.id);if(error)return setMsg(error.message);await load();setMsg('Layout deleted.')};
  const kinds:{value:Kind;label:string}[]=[{value:'invoice',label:'Invoice'},{value:'quote',label:'Quote / Cost Estimate'},{value:'credit_note',label:'Credit Note'}];const german=form.language_code==='de';
  return <div className="max-w-6xl"><h1 className="text-3xl font-bold">Document layouts</h1><p className="text-gray-600 mt-1 mb-4">Create multiple layouts for {workspace?.legal_name}, choose their language, and select one on each document.</p><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{kinds.map(item=><button type="button" key={item.value} onClick={()=>setKind(item.value)} className={`whitespace-nowrap rounded-lg border px-4 py-2 text-sm font-medium ${kind===item.value?'border-blue-600 bg-blue-600 text-white':'border-gray-300 bg-white text-gray-700'}`}>{item.label}</button>)}</div>
  <div className="mb-6 flex flex-wrap items-end gap-3"><Select label="Saved layouts" value={form.id} onChange={e=>void apply(templates.find(x=>x.id===e.target.value)||null)}><option value="">New layout</option>{templates.map(x=><option key={x.id} value={x.id}>{x.name}{x.is_default?' (default)':''}</option>)}</Select><Button variant="secondary" onClick={()=>void apply({...empty,name:`${workspace?.country==='AT'?'Austrian':'FZCO'} ${kinds.find(x=>x.value===kind)?.label} English`,is_default:templates.length===0})}>New layout</Button></div>
  <div className="grid gap-6 lg:grid-cols-2"><form onSubmit={save} className="space-y-4 bg-white border rounded-xl p-4 sm:p-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">{form.id?'Editing layout':'Creating layout'}</p><h2 className="text-xl font-semibold">{form.name||'New layout'}</h2></div><div className="grid sm:grid-cols-2 gap-3"><Input required label="Layout name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Select label="Document language" value={form.language_code} onChange={e=>setForm({...form,language_code:e.target.value})}><option value="en">English</option><option value="de">Deutsch</option></Select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_default} onChange={e=>setForm({...form,is_default:e.target.checked})}/>Use as the default {kind.replace('_',' ')} layout for this company</label><div className="grid grid-cols-2 gap-3"><Select label="Font" value={form.font_family} onChange={e=>setForm({...form,font_family:e.target.value})}><option value="helvetica">Helvetica</option><option value="times">Times</option><option value="courier">Courier</option></Select><Input type="color" label="Accent colour" value={form.accent_color} onChange={e=>setForm({...form,accent_color:e.target.value})}/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Logo</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}} className="block w-full text-sm"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Payment instructions</label><textarea rows={5} value={form.payment_instructions} onChange={e=>setForm({...form,payment_instructions:e.target.value})} placeholder={'Account Holder:\nBank:\nIBAN:\nBIC:'} className="w-full rounded-lg border border-gray-300 px-3 py-2"/></div><Input type="number" min="6" max="16" step="0.5" label="Payment instruction text size" value={form.payment_instructions_font_size} onChange={e=>setForm({...form,payment_instructions_font_size:e.target.value})}/><div><label className="block text-sm font-medium text-gray-700 mb-1">Footer text</label><textarea rows={4} value={form.footer_text} onChange={e=>setForm({...form,footer_text:e.target.value})} className="w-full rounded-lg border border-gray-300 px-3 py-2"/></div><div className="flex gap-2"><Button type="submit" disabled={busy}>{busy?'Saving…':'Save layout'}</Button>{form.id&&<Button type="button" variant="danger" onClick={remove}>Delete</Button>}</div>{msg&&<p className="text-sm text-blue-700">{msg}</p>}</form>
  <div className="bg-white border rounded-xl p-6 min-h-[520px] shadow-sm" style={{fontFamily:form.font_family}}><div className="h-1 rounded mb-6" style={{backgroundColor:form.accent_color}}/><div className="flex justify-between items-start">{logoUrl?<img src={logoUrl} alt="Company logo" className="max-h-16 max-w-40 object-contain"/>:<div className="h-12 w-28 rounded border border-dashed flex items-center justify-center text-xs text-gray-400">Logo</div>}<div className="text-right"><p className="text-2xl font-semibold">{kind==='quote'?(german?'KOSTENVORANSCHLAG':'COST ESTIMATE'):kind==='invoice'?(german?'RECHNUNG':'INVOICE'):(german?'GUTSCHRIFT':'CREDIT NOTE')}</p><p className="text-sm text-gray-500">No. 2026-0001</p></div></div><h2 className="text-lg font-semibold mt-8">{workspace?.legal_name}</h2><div className="mt-4 text-sm"><p className="font-semibold">{german?'Rechnung an':'Bill to'}</p><p>Example Customer GmbH</p><p>Example Street 1</p><p>1010 Vienna · Austria</p><p>UID / VAT ID: ATU12345678</p></div><p className="mt-3 rounded bg-gray-50 p-2 text-sm">{german?'Leistungsdatum: August 2026':'Service date: August 2026'}</p><div className="mt-8 border-y py-4 text-sm"><div className="flex justify-between"><span>Example service</span><span>{workspace?.base_currency} 1,000.00</span></div></div><div className="mt-5 text-right font-semibold">{german?'Gesamt':'Total'}: {workspace?.base_currency} 1,000.00</div><div className="mt-8 whitespace-pre-line text-gray-600" style={{fontSize:`${form.payment_instructions_font_size}px`}}>{form.payment_instructions||'Payment instructions'}</div><div className="mt-12 whitespace-pre-line border-t pt-3 text-xs text-gray-500">{form.footer_text||'Footer text'}</div></div></div></div>;
}
