import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {useApp} from '../contexts/AppContext';
import {Button} from '../components/Button';
import {Select} from '../components/Select';
interface Mailbox{id:string;mailbox:string;provider?:string;enabled:boolean;ai_enabled:boolean;last_attempt:string|null;last_success:string|null;last_error:string|null}
interface Alias{alias:string;workspace_id:string;mailbox_id:string}
export function EmailIngestionSettings(){
 const{workspaces}=useApp();const[boxes,setBoxes]=useState<Mailbox[]>([]),[aliases,setAliases]=useState<Alias[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const[b,a]=await Promise.all([supabase.from('receipt_mailboxes').select('id,mailbox,provider,enabled,ai_enabled,last_attempt,last_success,last_error'),supabase.from('receipt_aliases').select('*')]);if(b.error||a.error)throw b.error||a.error;setBoxes(b.data||[]);setAliases(a.data||[]);};
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 return <div className="max-w-3xl space-y-5"><h1 className="text-3xl font-bold">Receipt inboxes</h1><p>Mailbox access runs on the server. Secrets are never displayed here.</p>{error&&<p role="alert" className="text-red-800">{error}</p>}{notice&&<p>{notice}</p>}{boxes.length===0&&<p>No mailbox configured for your account.</p>}{boxes.map(b=><div key={b.id} className="bg-white border rounded-xl p-5 space-y-4"><h2 className="font-semibold">{b.mailbox}</h2>{b.provider==='postmark_inbound'?<p className="text-sm text-blue-800">Your private receipt address. Forward receipts here; they enter your review queue automatically.</p>:<p>Last successful sync: {b.last_success||'Not yet verified'}</p>}<p>Last attempt: {b.last_attempt||'None'}</p>{b.last_error&&<p className="text-red-700">{b.last_error}</p>}{b.provider!=='postmark_inbound'&&<label className="block"><input type="checkbox" checked={b.enabled} onChange={e=>setBoxes(boxes.map(x=>x.id===b.id?{...x,enabled:e.target.checked}:x))}/> Automatic ingestion</label>}<label className="block"><input type="checkbox" checked={b.ai_enabled} onChange={e=>setBoxes(boxes.map(x=>x.id===b.id?{...x,ai_enabled:e.target.checked}:x))}/> AI extraction fallback</label><p className="text-sm text-gray-600">Booking is available after review. Automatic booking requires a complete, verified account and tax policy.</p>{aliases.filter(a=>a.mailbox_id===b.id).map(a=><Select key={a.alias} label={a.alias} value={a.workspace_id} onChange={e=>setAliases(aliases.map(x=>x.alias===a.alias?{...x,workspace_id:e.target.value}:x))}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.legal_name}</option>)}</Select>)}{b.provider!=='postmark_inbound'&&<div className="flex gap-3"><Button disabled={busy} onClick={()=>void run(async()=>{const{error:e}=await supabase.rpc('configure_receipt_mailbox',{p_id:b.id,p_enabled:b.enabled,p_ai_enabled:b.ai_enabled,p_aliases:aliases.filter(a=>a.mailbox_id===b.id)});if(e)throw e;setNotice('Settings saved.');})}>Save settings</Button><Button disabled={busy} variant="secondary" onClick={()=>void run(async()=>{const{data,error:e}=await supabase.functions.invoke('ingest-receipts',{body:{mailbox_id:b.id}});if(e)throw e;if(data?.error)throw new Error(data.error);setNotice('Sync completed. Check the receipt inbox.');})}>Sync now</Button></div>}</div>)}<a className="text-blue-700" href="/receipt-inbox">Open receipt inbox</a></div>;
}
