import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { useApp } from '../contexts/AppContext'; import { supabase } from '../lib/supabase';
import { ProductService } from '../lib/types'; import { Button } from '../components/Button'; import { Input } from '../components/Input'; import { Select } from '../components/Select';
type Line={product_service_id:string;description:string;quantity:number;unit:string;unit_price:number;vat_code_id:string;vat_rate:number;revenue_account_id:string};
export function NewQuote(){const{workspaceId,workspace,counterparties,vatCodes}=useApp();const[items,setItems]=useState<ProductService[]>([]);const[customer,setCustomer]=useState('');const[valid,setValid]=useState('');const[lines,setLines]=useState<Line[]>([]);const[msg,setMsg]=useState('');
useEffect(()=>{setValid(new Date(Date.now()+14*86400000).toISOString().slice(0,10));if(workspaceId)supabase.from('products_services').select('*').eq('workspace_id',workspaceId).eq('is_active',true).then(({data})=>setItems((data||[])as ProductService[]));},[workspaceId]);
const add=()=>setLines([...lines,{product_service_id:'',description:'',quantity:1,unit:'each',unit_price:0,vat_code_id:'',vat_rate:0,revenue_account_id:''}]);
const choose=(i:number,id:string)=>{const item=items.find(x=>x.id===id);if(!item)return;const vat=vatCodes.find(x=>x.id===item.vat_code_id);const copy=[...lines];copy[i]={product_service_id:id,description:item.description||item.name,quantity:1,unit:item.unit,unit_price:Number(item.unit_price),vat_code_id:item.vat_code_id||'',vat_rate:Number(vat?.vat_rate||0),revenue_account_id:item.revenue_account_id||''};setLines(copy);};
const totals=useMemo(()=>lines.reduce((a,l)=>{const n=l.quantity*l.unit_price;return{net:a.net+n,tax:a.tax+n*l.vat_rate};},{net:0,tax:0}),[lines]);
const save=async(e:FormEvent)=>{e.preventDefault();if(!workspaceId||!workspace||!customer||!lines.length)return setMsg('Choose a customer and add at least one line.');setMsg('Saving…');const issue=new Date().toISOString().slice(0,10);const{data:doc,error}=await supabase.from('sales_documents').insert({workspace_id:workspaceId,document_type:'quote',customer_id:customer,issue_date:issue,valid_until:valid,currency:workspace.base_currency,status:'draft',subtotal:totals.net,tax_total:totals.tax,total:totals.net+totals.tax}).select('id').single();if(error||!doc)return setMsg(error?.message||'Could not save quote');const payload=lines.map((l,i)=>({workspace_id:workspaceId,document_id:doc.id,line_no:i+1,...l,net_amount:l.quantity*l.unit_price,vat_amount:l.quantity*l.unit_price*l.vat_rate,gross_amount:l.quantity*l.unit_price*(1+l.vat_rate),discount_percent:0}));const{error:lineError}=await supabase.from('sales_document_lines').insert(payload);if(lineError)return setMsg(lineError.message);window.history.pushState({},'','/sales-documents');window.dispatchEvent(new PopStateEvent('popstate'));};
return <div className="max-w-6xl"><h1 className="text-3xl font-bold">New quote</h1><p className="text-gray-600 mt-1 mb-6">Create a cost estimate for {workspace?.legal_name}.</p><form onSubmit={save} className="space-y-5"><div className="bg-white border rounded-xl p-5 grid md:grid-cols-2 gap-4"><Select required label="Customer" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Choose customer</option>{counterparties.filter(c=>c.kind!=='vendor').map(c=><option key={c.id} value={c.id}>{c.company_name||c.name}</option>)}</Select><Input type="date" label="Valid until" value={valid} onChange={e=>setValid(e.target.value)}/></div>
<div className="bg-white border rounded-xl overflow-hidden"><div className="p-4 flex justify-between"><h2 className="font-semibold">Line items</h2><Button type="button" size="sm" onClick={add}><Plus className="w-4 h-4 mr-1"/>Add line</Button></div>{lines.map((l,i)=><div key={i} className="border-t p-4 grid md:grid-cols-12 gap-3 items-end"><div className="md:col-span-3"><Select label="Item" value={l.product_service_id} onChange={e=>choose(i,e.target.value)}><option value="">Choose item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></div><div className="md:col-span-4"><Input label="Description" value={l.description} onChange={e=>{const c=[...lines];c[i].description=e.target.value;setLines(c)}}/></div><div className="md:col-span-2"><Input type="number" step="0.01" label="Quantity" value={l.quantity} onChange={e=>{const c=[...lines];c[i].quantity=Number(e.target.value);setLines(c)}}/></div><div className="md:col-span-2"><Input type="number" step="0.01" label="Unit price" value={l.unit_price} onChange={e=>{const c=[...lines];c[i].unit_price=Number(e.target.value);setLines(c)}}/></div><button type="button" onClick={()=>setLines(lines.filter((_,x)=>x!==i))} className="p-2 text-red-600"><Trash2 className="w-5 h-5"/></button></div>)}{!lines.length&&<p className="p-8 border-t text-center text-gray-500">Add a product or service.</p>}<div className="border-t bg-gray-50 p-4 text-right"><p>Subtotal: {workspace?.base_currency} {totals.net.toFixed(2)}</p><p>Tax: {totals.tax.toFixed(2)}</p><p className="text-lg font-bold mt-1">Total: {(totals.net+totals.tax).toFixed(2)}</p></div></div>{msg&&<p className="text-sm text-amber-700">{msg}</p>}<div className="flex justify-end"><Button type="submit">Save draft quote</Button></div></form></div>}
