import{FormEvent,useEffect,useMemo,useState}from'react';
import{AlertTriangle,CalendarDays,CheckCircle2,Download,Landmark,Plus,Search}from'lucide-react';
import{supabase}from'../lib/supabase';import{Button}from'../components/Button';import{Input}from'../components/Input';import{Modal}from'../components/Modal';
type Case={id:string;name:string};type Row={schedule_id:string;creditor:string;due_date:string;amount_due:number;amount_paid:number;balance:number;status:'paid'|'overdue'|'due'};type Tab='overview'|'open'|'paid'|'creditors';
const euro=(n:number)=>new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(Number(n||0));const today=()=>new Date().toISOString().slice(0,10);const monthKey=(d:string)=>d.slice(0,7);
function downloadCsv(name:string,rows:Row[]){const head=['Creditor','Due date','Amount due','Paid','Open','Status'];const cells=rows.map(r=>[r.creditor,r.due_date,r.amount_due,r.amount_paid,r.balance,r.status]);const csv=[head,...cells].map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export function PrivateInsolvency(){const[caseRow,setCaseRow]=useState<Case|null>(null);const[rows,setRows]=useState<Row[]>([]);const[tab,setTab]=useState<Tab>('overview');const[query,setQuery]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(true);const[target,setTarget]=useState<Row|null>(null);const[amount,setAmount]=useState('');const[date,setDate]=useState(today());
 const load=async()=>{setBusy(true);setMsg('');const{data:{user}}=await supabase.auth.getUser();if(!user)return setBusy(false);let{data:c,error}=await supabase.from('private_insolvency_cases').select('id,name').maybeSingle();if(error&&error.code!=='PGRST116'){setMsg(error.message);return setBusy(false)}if(!c){const created=await supabase.from('private_insolvency_cases').insert({owner_user_id:user.id,name:'Private Insolvency',currency:'EUR'}).select('id,name').single();if(created.error){setMsg(created.error.message);return setBusy(false)}c=created.data}setCaseRow(c as Case);const result=await supabase.from('v_private_insolvency_schedule').select('*').eq('case_id',c.id).order('due_date');if(result.error)setMsg(result.error.message);else setRows((result.data||[])as Row[]);setBusy(false)};
 useEffect(()=>{void load()},[]);const now=today(),thisMonth=monthKey(now),nextMonth=monthKey(new Date(new Date().getFullYear(),new Date().getMonth()+1,1).toISOString());
 const buckets=useMemo(()=>({overdue:rows.filter(r=>r.status==='overdue'),month:rows.filter(r=>r.status!=='paid'&&monthKey(r.due_date)===thisMonth),next:rows.filter(r=>r.status!=='paid'&&monthKey(r.due_date)===nextMonth),open:rows.filter(r=>r.status!=='paid'),paid:rows.filter(r=>r.status==='paid')}),[rows,thisMonth,nextMonth]);
 const totals=useMemo(()=>({due:rows.reduce((s,r)=>s+Number(r.amount_due),0),paid:rows.reduce((s,r)=>s+Number(r.amount_paid),0),open:buckets.open.reduce((s,r)=>s+Math.max(Number(r.balance),0),0)}),[rows,buckets.open]);
 const filtered=(tab==='paid'?buckets.paid:buckets.open).filter(r=>r.creditor.toLowerCase().includes(query.toLowerCase()));const creditorRows=useMemo(()=>Object.values(rows.reduce((a,r)=>{const x=a[r.creditor]||{creditor:r.creditor,due:0,paid:0,open:0,next:''};x.due+=Number(r.amount_due);x.paid+=Number(r.amount_paid);x.open+=Math.max(Number(r.balance),0);if(r.status!=='paid'&&(!x.next||r.due_date<x.next))x.next=r.due_date;a[r.creditor]=x;return a},{}as Record<string,{creditor:string;due:number;paid:number;open:number;next:string}>)).sort((a,b)=>b.open-a.open),[rows]);
 const pay=async(e:FormEvent)=>{e.preventDefault();if(!target)return;setMsg('Saving…');const{error}=await supabase.rpc('record_private_insolvency_payment',{p_schedule_id:target.schedule_id,p_amount:Number(amount),p_paid_date:date,p_note:'Recorded in Accountant'});if(error)return setMsg(error.message);setTarget(null);await load()};const openPay=(r:Row)=>{setTarget(r);setAmount(Math.max(Number(r.balance),0).toFixed(2));setDate(today())};
 if(busy)return<p className="text-gray-600">Loading private insolvency…</p>;
 const Payment=({r,compact=false}:{r:Row;compact?:boolean})=><div className={`rounded-lg border bg-white ${compact?'p-3':'p-4'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{r.creditor}</p><p className="mt-1 text-xs text-gray-500">Due {r.due_date} · {euro(r.amount_due)}</p>{Number(r.amount_paid)>0&&<p className="text-xs text-green-700">Paid {euro(r.amount_paid)}</p>}</div><div className="text-right"><p className="font-bold">{euro(Math.max(r.balance,0))}</p><span className={`text-xs font-medium ${r.status==='overdue'?'text-red-700':r.status==='paid'?'text-green-700':'text-amber-700'}`}>{r.status}</span></div></div>{r.status!=='paid'&&<Button size="sm"className="mt-3 w-full"onClick={()=>openPay(r)}><CheckCircle2 className="mr-1 inline h-4 w-4"/>Record payment</Button>}</div>;
 const Lane=({title,data,tone}:{title:string;data:Row[];tone:string})=><section className={`rounded-xl border-2 p-3 ${tone}`}><div className="mb-3 flex items-start justify-between"><div><h2 className="font-semibold">{title}</h2><p className="text-sm font-bold">{euro(data.reduce((s,r)=>s+Math.max(r.balance,0),0))}</p></div><span className="rounded-full bg-white px-2 py-1 text-xs">{data.length}</span></div><div className="space-y-2">{data.slice(0,6).map(r=><Payment key={r.schedule_id}r={r}compact/>)}{!data.length&&<p className="py-6 text-center text-sm text-gray-500">Nothing here</p>}{data.length>6&&<button className="w-full py-2 text-sm font-medium text-purple-700"onClick={()=>setTab('open')}>View all {data.length}</button>}</div></section>;
 return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-purple-700">Private · excluded from company accounting</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">{caseRow?.name}</h1><p className="mt-1 text-sm text-gray-600">Payment plans, deadlines and progress</p></div><Button variant="secondary"onClick={()=>downloadCsv(`private-insolvency-${tab}-${today()}.csv`,tab==='paid'?buckets.paid:buckets.open)}><Download className="mr-2 inline h-4 w-4"/>Export CSV</Button></div>{msg&&<div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{msg}</div>}
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[Landmark,'Plan total',euro(totals.due)],[CheckCircle2,'Paid',euro(totals.paid)],[CalendarDays,'Open',euro(totals.open)],[AlertTriangle,'Overdue',String(buckets.overdue.length)]].map(([Icon,label,value])=>{const I=Icon as typeof Landmark;return <div key={label as string}className="rounded-xl border bg-white p-4"><I className="h-5 w-5 text-purple-600"/><p className="mt-2 text-xs uppercase text-gray-500">{label as string}</p><p className="mt-1 text-xl font-bold">{value as string}</p></div>})}</div>
 <div className="flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{([['overview','Overview'],['open','All open'],['paid','Paid'],['creditors','Creditors']]as[Tab,string][]).map(([id,label])=><button key={id}onClick={()=>setTab(id)}className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-medium ${tab===id?'bg-purple-700 text-white':'text-gray-600 hover:bg-gray-100'}`}>{label}</button>)}</div>
 {tab==='overview'&&<div className="grid gap-4 lg:grid-cols-3"><Lane title="Overdue"data={buckets.overdue}tone="border-red-200 bg-red-50"/><Lane title="This month"data={buckets.month}tone="border-amber-200 bg-amber-50"/><Lane title="Next month"data={buckets.next}tone="border-blue-200 bg-blue-50"/></div>}
 {(tab==='open'||tab==='paid')&&<div className="space-y-3"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Search creditor"className="w-full rounded-lg border py-2.5 pl-10 pr-3"/></div><p className="text-sm text-gray-500">{filtered.length} instalments · {euro(filtered.reduce((s,r)=>s+(tab==='paid'?r.amount_paid:Math.max(r.balance,0)),0))}</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><Payment key={r.schedule_id}r={r}/>)}</div></div>}
 {tab==='creditors'&&<div className="overflow-hidden rounded-xl border bg-white"><div className="divide-y">{creditorRows.map(r=><div key={r.creditor}className="grid grid-cols-2 gap-2 p-4 sm:grid-cols-5"><p className="col-span-2 font-semibold sm:col-span-1">{r.creditor}</p><p className="text-sm"><span className="text-gray-500">Plan</span><br/>{euro(r.due)}</p><p className="text-sm"><span className="text-gray-500">Paid</span><br/>{euro(r.paid)}</p><p className="text-sm font-semibold"><span className="text-gray-500">Open</span><br/>{euro(r.open)}</p><p className="text-sm"><span className="text-gray-500">Next due</span><br/>{r.next||'Complete'}</p></div>)}</div></div>}
 <Modal isOpen={!!target}onClose={()=>setTarget(null)}title={`Record payment · ${target?.creditor||''}`}><form onSubmit={pay}className="space-y-4"><Input label="Amount (EUR)"type="number"step="0.01"min="0.01"required value={amount}onChange={e=>setAmount(e.target.value)}/><Input label="Payment date"type="date"required value={date}onChange={e=>setDate(e.target.value)}/><div className="flex justify-end gap-2"><Button type="button"variant="secondary"onClick={()=>setTarget(null)}>Cancel</Button><Button type="submit"><Plus className="mr-1 inline h-4 w-4"/>Save payment</Button></div></form></Modal></div>}
