import{FormEvent,useEffect,useMemo,useState}from'react';
import{AlertCircle,CalendarClock,CheckCircle2,Landmark,Plus}from'lucide-react';
import{supabase}from'../lib/supabase';import{Button}from'../components/Button';import{Input}from'../components/Input';import{Modal}from'../components/Modal';
type Case={id:string;name:string;currency:string};type Row={schedule_id:string;creditor:string;due_date:string;amount_due:number;amount_paid:number;balance:number;status:string};
const money=(n:number)=>new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(Number(n||0));
export function PrivateInsolvency(){const[caseRow,setCaseRow]=useState<Case|null>(null);const[rows,setRows]=useState<Row[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(true);const[target,setTarget]=useState<Row|null>(null);const[amount,setAmount]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const load=async()=>{setBusy(true);setMsg('');const{data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return}let{data:c,error}=await supabase.from('private_insolvency_cases').select('id,name,currency').maybeSingle();if(error&&error.code!=='PGRST116'){setMsg(error.message);setBusy(false);return}if(!c){const created=await supabase.from('private_insolvency_cases').insert({owner_user_id:user.id,name:'Private Insolvency',currency:'EUR'}).select('id,name,currency').single();if(created.error){setMsg(created.error.message);setBusy(false);return}c=created.data}setCaseRow(c as Case);const result=await supabase.from('v_private_insolvency_schedule').select('*').eq('case_id',c.id).order('due_date');if(result.error)setMsg(result.error.message);else setRows((result.data||[])as Row[]);setBusy(false)};
 useEffect(()=>{void load()},[]);const totals=useMemo(()=>rows.reduce((a,r)=>({due:a.due+Number(r.amount_due),paid:a.paid+Number(r.amount_paid),open:a.open+Math.max(Number(r.balance),0),overdue:a.overdue+(r.status==='overdue'?1:0)}),{due:0,paid:0,open:0,overdue:0}),[rows]);
 const pay=async(e:FormEvent)=>{e.preventDefault();if(!target)return;setMsg('Saving…');const{error}=await supabase.rpc('record_private_insolvency_payment',{p_schedule_id:target.schedule_id,p_amount:Number(amount),p_paid_date:date,p_note:'Recorded in Accountant'});if(error)return setMsg(error.message);setTarget(null);await load()};
 const openPay=(r:Row)=>{setTarget(r);setAmount(String(Math.max(Number(r.balance),0).toFixed(2)))};
 if(busy)return<p className="text-gray-600">Loading private insolvency…</p>;
 return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-wider text-purple-700">Private · excluded from company accounting</p><h1 className="mt-1 text-3xl font-bold">{caseRow?.name||'Private Insolvency'}</h1><p className="mt-1 text-gray-600">Payment-plan tracking only. Never included in P&amp;L, VAT or FinanzOnline.</p></div>{msg&&<div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{msg}</div>}
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[Landmark,'Plan total',money(totals.due)],[CheckCircle2,'Paid',money(totals.paid)],[CalendarClock,'Open',money(totals.open)],[AlertCircle,'Overdue',String(totals.overdue)]].map(([Icon,label,value])=>{const I=Icon as typeof Landmark;return <div key={label as string}className="rounded-xl border bg-white p-4"><I className="h-5 w-5 text-purple-600"/><p className="mt-3 text-xs uppercase text-gray-500">{label as string}</p><p className="mt-1 text-xl font-bold">{value as string}</p></div>})}</div>
 <div className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">Payment schedule</h2></div><div className="divide-y lg:hidden">{rows.map(r=><div key={r.schedule_id}className="p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{r.creditor}</p><p className="text-sm text-gray-500">Due {r.due_date} · {r.status}</p></div><p className="font-semibold">{money(r.balance)}</p></div>{r.status!=='paid'&&<Button size="sm"className="mt-3 w-full"onClick={()=>openPay(r)}><Plus className="mr-1 inline h-4 w-4"/>Record payment</Button>}</div>)}</div><div className="hidden overflow-x-auto lg:block"><table className="w-full text-left"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="p-4">Creditor</th><th>Due</th><th>Amount</th><th>Paid</th><th>Open</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.schedule_id}className="border-t"><td className="p-4 font-medium">{r.creditor}</td><td>{r.due_date}</td><td>{money(r.amount_due)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance)}</td><td className="capitalize">{r.status}</td><td className="pr-4 text-right">{r.status!=='paid'&&<Button size="sm"onClick={()=>openPay(r)}>Record payment</Button>}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="p-10 text-center text-gray-500">No migrated payment schedule yet.</p>}</div>
 <Modal isOpen={!!target}onClose={()=>setTarget(null)}title={`Record payment · ${target?.creditor||''}`}><form onSubmit={pay}className="space-y-4"><Input label="Amount (EUR)"type="number"step="0.01"min="0.01"required value={amount}onChange={e=>setAmount(e.target.value)}/><Input label="Payment date"type="date"required value={date}onChange={e=>setDate(e.target.value)}/><div className="flex justify-end gap-2"><Button type="button"variant="secondary"onClick={()=>setTarget(null)}>Cancel</Button><Button type="submit">Save payment</Button></div></form></Modal></div>}
