import { useEffect, useState } from 'react';
import { useApp } from '../contexts/AppContext';
import { supabase } from '../lib/supabase';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { Select } from '../components/Select';
import { Account, VatCode } from '../lib/types';
import { Allocation, Booking, Receipt, allocationAmounts, bookingFor, emptyLine } from '../features/receipts/model';

export function ReceiptInbox() {
 const {workspaces}=useApp();
 const [rows,setRows]=useState<Receipt[]>([]),[selected,setSelected]=useState<Receipt|null>(null);
 const [booking,setBooking]=useState<Booking|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[codes,setCodes]=useState<VatCode[]>([]);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState('Reviewed receipt');
 const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});
 const [filter,setFilter]=useState('needs_review'),[page,setPage]=useState(0);
 const load=async()=>{setError('');const q=supabase.from('receipt_candidates').select('*').order('created_at',{ascending:false}).range(page*50,page*50+49);const {data,error:e}=await(filter==='all'?q:q.eq('status',filter));if(e)setError(e.message);else setRows(data||[]);};
 useEffect(()=>{void load();},[filter,page]);
 useEffect(()=>{let active=true;setAccounts([]);setCodes([]);if(selected?.workspace_id)void Promise.all([supabase.from('accounts').select('*').eq('workspace_id',selected.workspace_id).eq('is_active',true).order('code'),supabase.from('vat_codes').select('*').eq('workspace_id',selected.workspace_id)]).then(([a,v])=>{if(!active)return;if(a.error||v.error)setError(a.error?.message||v.error?.message||'Could not load accounts');else{setAccounts(a.data||[]);setCodes(v.data||[]);}});return()=>{active=false};},[selected?.workspace_id]);
 const fieldsForError=(message:string)=>{
  if(/Document tax treatment and business purpose/i.test(message))return {tax_reason:'Explain the business purpose, tax treatment and any participants.'};
  if(/Select payment, payable or clearing account/i.test(message))return {counter_account_id:'Select the account used to pay, owe or clear this receipt.'};
  if(/Select input VAT account/i.test(message))return {vat_account_id:'Select the input VAT account for the recoverable VAT.'};
  if(/Select private \/ shareholder clearing account/i.test(message))return {private_account_id:'Select the account for the private share.'};
  if(/Select non-deductible business expense account/i.test(message))return {nondeductible_account_id:'Select the account for the non-deductible share.'};
  if(/Invalid booking account/i.test(message))return {allocation_account:'Choose a valid booking account in this company.'};
  if(/Invalid amounts or allocation percentages/i.test(message))return {allocation_values:'Check the amount, VAT and percentage values in this allocation.'};
  if(/Enter a verified exchange rate/i.test(message))return {fx_rate:'For a EUR receipt in the EU company, enter 1. For another currency, enter the verified conversion rate.'};
  return {};
 };
 const errorMessage=(e:unknown)=>{
  if(e instanceof Error)return e.message;
  if(e&&typeof e==='object'){
   const value=e as {message?:unknown;details?:unknown;hint?:unknown};
   const parts=[value.message,value.details,value.hint].filter((part):part is string=>typeof part==='string'&&part.trim().length>0);
   if(parts.length)return parts.join(' ');
  }
  return 'The receipt could not be saved. Check the highlighted fields and try again.';
 };
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();setFieldErrors({});await load();}catch(e){const message=errorMessage(e);setError(message);setFieldErrors(fieldsForError(message));}finally{setBusy(false)}};
 const open=(r:Receipt)=>{setSelected(r);setBooking(bookingFor(r));setReason(r.status==='booked'?'':'Reviewed receipt');setError('');setNotice('');setFieldErrors({});};
 const save=async(book:boolean)=>{if(!selected||!booking)return;const payload={...selected,booking};
 if(selected.status==='booked'){const {error:e}=await supabase.rpc('correct_receipt',{p_id:selected.id,p_revision:selected.revision,p_data:payload,p_reason:reason});if(e)throw e;setNotice('Booking corrected. Original and reversal retained.');}
 else{const {data:revision,error:e}=await supabase.rpc('save_receipt',{p_id:selected.id,p_revision:selected.revision,p_data:payload,p_reason:reason});if(e)throw e;setSelected({...selected,booking,revision});if(book){const{error:b}=await supabase.rpc('book_receipt',{p_id:selected.id,p_revision:revision,p_reason:reason});if(b)throw b;}setNotice(book?'Receipt booked. Its reviewed details will prefill future 75% similar receipts for approval.':'Changes saved.');}setSelected(null);};
 const action=async(value:string)=>{if(!selected)return;const {error:e}=await supabase.rpc('receipt_action',{p_id:selected.id,p_revision:selected.revision,p_action:value,p_reason:reason});if(e)throw e;setSelected(null);};
 const line=(i:number,key:keyof Allocation,value:string|number)=>{if(!booking)return;setFieldErrors({});setBooking({...booking,lines:booking.lines.map((l,j)=>j===i?{...l,[key]:value}:l)});};
 const accountSelect=(label:string,key:'counter_account_id'|'vat_account_id'|'private_account_id'|'nondeductible_account_id')=>booking&&<Select label={label} error={fieldErrors[key]} value={booking[key]} onChange={e=>{setFieldErrors({});setBooking({...booking,[key]:e.target.value});}}><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select>;
 return <div className="max-w-6xl space-y-5"><div><h1 className="text-3xl font-bold">Receipt inbox</h1><p className="text-gray-600">Review, book and correct receipts. Original documents and booking history are retained.</p></div>
 <div className="flex gap-3 items-end"><Select label="Status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}>{['needs_review','received','failed','booked','duplicate','ignored','all'].map(s=><option key={s}>{s}</option>)}</Select><Button disabled={busy} onClick={()=>void run(load)}>Refresh</Button><a className="text-blue-700 p-2" href="/email-ingestion">Microsoft 365 settings</a></div>
 {error&&<p role="alert" className="bg-red-50 text-red-800 p-3 rounded">{error}</p>}{notice&&<p role="status" className="bg-green-50 text-green-800 p-3">{notice}</p>}
 {!selected?<><div className="bg-white border rounded-xl divide-y">{rows.length===0?<p className="p-6">{error?'Could not load receipts.':'No receipts in this view.'}</p>:rows.map(r=><button key={r.id} onClick={()=>open(r)} className="w-full text-left p-4 hover:bg-gray-50"><div className="flex justify-between gap-4"><strong>{r.vendor||r.filename||'Unidentified receipt'}</strong><span>{r.currency} {r.gross_amount??'—'}</span></div><p className="text-sm text-gray-600">{workspaces.find(w=>w.id===r.workspace_id)?.legal_name||'Company needs review'} · {r.document_date||'Date needs review'} · {r.status}</p><p className="text-sm text-amber-800">{r.failure_reason||r.review_reasons.join(' · ')}</p></button>)}</div><div className="flex gap-2"><Button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><span className="p-2">Page {page+1}</span><Button disabled={rows.length<50} onClick={()=>setPage(page+1)}>Next</Button></div></>:booking&&<div className="bg-white border rounded-xl p-5 space-y-5">
 <div className="flex justify-between"><h2 className="text-xl font-semibold">{selected.status==='booked'?'Correct booked receipt':'Receipt details'}</h2><Button variant="secondary" onClick={()=>setSelected(null)}>Close</Button></div>
 <p className="text-sm text-gray-600">Received through {selected.receiving_alias||'unresolved alias'} · {selected.filename} · revision {selected.revision}</p>
 {selected.file_path&&<Button variant="secondary" onClick={()=>void run(async()=>{const{data,error:e}=await supabase.storage.from('receipt-originals').createSignedUrl(selected.file_path!,120);if(e)throw e;window.open(data.signedUrl,'_blank','noopener,noreferrer');})}>Open original document</Button>}
 <div className="grid sm:grid-cols-2 gap-4"><Select label="Company" value={selected.workspace_id||''} onChange={e=>{setFieldErrors({});setSelected({...selected,workspace_id:e.target.value||null});setBooking({...booking,counter_account_id:'',vat_account_id:'',private_account_id:'',nondeductible_account_id:'',fx_rate:1,lines:booking.lines.map(l=>({...l,account_id:'',vat_code_id:'',vat_recovery_percent:0}))});}}><option value="">Needs review</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.country==='AT'?'EU':w.country==='AE'?'FZCO':w.country} · {w.legal_name}</option>)}</Select>
 <Input label="Vendor / merchant" value={selected.vendor||''} onChange={e=>setSelected({...selected,vendor:e.target.value})}/><Input label="Invoice / receipt number" value={selected.invoice_number||''} onChange={e=>setSelected({...selected,invoice_number:e.target.value})}/><Input type="date" label="Document date" value={selected.document_date||''} onChange={e=>setSelected({...selected,document_date:e.target.value})}/><Input type="date" label="Due date (optional)" value={selected.due_date||''} onChange={e=>setSelected({...selected,due_date:e.target.value})}/><Input label="Currency" value={selected.currency||''} maxLength={3} onChange={e=>setSelected({...selected,currency:e.target.value.toUpperCase()})}/><Input label="Original gross total" type="number" step=".01" value={selected.gross_amount??''} onChange={e=>setSelected({...selected,gross_amount:e.target.value===''?null:Number(e.target.value)})}/><Input label="Exchange rate to company currency (1 for same currency)" error={fieldErrors.fx_rate} type="number" step=".000001" value={booking.fx_rate} onChange={e=>{setFieldErrors({});setBooking({...booking,fx_rate:Number(e.target.value)});}}/></div>
 <Input label="Booking description" value={selected.description} onChange={e=>setSelected({...selected,description:e.target.value})}/>
 <div className="bg-blue-50 p-3 rounded text-sm">Private use, tax deductibility and input VAT recovery are separate. Austrian business entertainment may be 50% expense-deductible with full input VAT recovery when the conditions are met. Record purpose and participants; 100% business use alone does not establish 100% deductibility.</div>
 {booking.lines.map((l,i)=><div key={i} className={`border rounded-lg p-4 space-y-3 ${fieldErrors.allocation_values?'border-red-500 bg-red-50':''}`}><div className="flex justify-between"><h3 className="font-semibold">Allocation {i+1}</h3>{booking.lines.length>1&&<Button variant="secondary" onClick={()=>setBooking({...booking,lines:booking.lines.filter((_,j)=>j!==i)})}>Remove</Button>}</div><div className="grid sm:grid-cols-3 gap-3"><Select label="Booking account" error={fieldErrors.allocation_account} value={l.account_id} onChange={e=>line(i,'account_id',e.target.value)}><option value="">Choose account</option>{accounts.filter(a=>['expense','cogs','asset'].includes(a.type)).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</Select><Input label="Line description" value={l.description} onChange={e=>line(i,'description',e.target.value)}/><Input label="Gross amount" error={fieldErrors.allocation_values} type="number" step=".01" value={l.gross} onChange={e=>line(i,'gross',Number(e.target.value))}/><Select label="VAT code" value={l.vat_code_id} onChange={e=>line(i,'vat_code_id',e.target.value)}><option value="">Manual / no code</option>{codes.filter(c=>c.applies_to!=='sales').map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</Select><Input label="VAT rate % (manual allowed)" error={fieldErrors.allocation_values} list="receipt-tax-rates" type="number" step=".01" value={l.tax_rate} onChange={e=>line(i,'tax_rate',Number(e.target.value))}/><Input label="VAT amount on receipt" error={fieldErrors.allocation_values} type="number" step=".01" value={l.tax} onChange={e=>line(i,'tax',Number(e.target.value))}/><Input label="Private use %" error={fieldErrors.allocation_values} type="number" min="0" max="100" value={l.private_percent} onChange={e=>line(i,'private_percent',Number(e.target.value))}/><Input label="Business expense deductible %" error={fieldErrors.allocation_values} type="number" min="0" max="100" value={l.deductible_percent} onChange={e=>line(i,'deductible_percent',Number(e.target.value))}/><Input label="Input VAT recoverable % of business share" error={fieldErrors.allocation_values} type="number" min="0" max="100" value={l.vat_recovery_percent} onChange={e=>line(i,'vat_recovery_percent',Number(e.target.value))}/></div><Button variant="secondary" onClick={()=>line(i,'tax',Math.round((l.gross-l.gross/(1+l.tax_rate/100))*100)/100)}>Calculate VAT from rate</Button><p className="text-sm text-gray-600">{(()=>{try{const a=allocationAmounts(l);return `Private ${a.privateAmount.toFixed(2)} · Input VAT ${a.recoverableVat.toFixed(2)} · Deductible expense ${a.deductible.toFixed(2)} · Non-deductible expense ${a.nonDeductible.toFixed(2)}`;}catch{return 'Check allocation values';}})()}</p></div>)}
 <datalist id="receipt-tax-rates">{[0,10,13,20].map(v=><option key={v} value={v}/>)}</datalist><Button variant="secondary" onClick={()=>setBooking({...booking,lines:[...booking.lines,emptyLine()]})}>Add tax / account allocation</Button><p>Allocated: {booking.lines.reduce((s,l)=>s+l.gross,0).toFixed(2)} {selected.currency}</p>
 <div className="grid sm:grid-cols-2 gap-3">{accountSelect('Paid from / payable / clearing account','counter_account_id')}{accountSelect('Input VAT account','vat_account_id')}{accountSelect('Private / shareholder clearing account','private_account_id')}{accountSelect('Non-deductible business expense account','nondeductible_account_id')}</div>
 <><Input label="Tax treatment, business purpose and participants" error={fieldErrors.tax_reason} value={booking.tax_reason} onChange={e=>{setFieldErrors({});setBooking({...booking,tax_reason:e.target.value});}}/>{selected.duplicate_status==='possible_duplicate'&&<Input label="Why this possible duplicate is a separate expense" value={booking.duplicate_override_reason} onChange={e=>setBooking({...booking,duplicate_override_reason:e.target.value})}/>}<Input label="Change / correction reason" value={reason} onChange={e=>setReason(e.target.value)}/></>
 <div className="flex flex-wrap gap-3">{selected.status!=='booked'&&<Button disabled={busy} variant="secondary" onClick={()=>void run(()=>save(false))}>Save edits</Button>}<Button disabled={busy} onClick={()=>void run(()=>save(true))}>{selected.status==='booked'?'Correct booking (reverse and replace)':'Approve and book'}</Button>{selected.status!=='booked'&&<><Button disabled={busy} variant="secondary" onClick={()=>void run(()=>action('duplicate'))}>Mark duplicate</Button><Button disabled={busy} variant="secondary" onClick={()=>void run(()=>action('ignored'))}>Ignore</Button><Button disabled={busy} variant="secondary" onClick={()=>void run(()=>action('retry'))}>Retry extraction</Button></>}</div>
 </div>}
 </div>;
}
