import { useEffect, useState } from 'react';
import { useApp } from '../contexts/AppContext';
import { supabase } from '../lib/supabase';
import { Button } from '../components/Button';

type Invoice={invoice_id:string;document_number:string;due_date:string|null;currency:string;total:number;amount_paid:number;amount_due:number;is_overdue:boolean};
type Reminder={invoice_id:string;reminder_level:number;status:string;reminder_date:string;late_fee_amount:number};
type Referral={invoice_id:string;status:string;recipient_email:string};

export function Receivables(){
  const{workspaceId}=useApp();const[rows,setRows]=useState<Invoice[]>([]);const[reminders,setReminders]=useState<Reminder[]>([]);const[referrals,setReferrals]=useState<Referral[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState('');
  const load=async()=>{if(!workspaceId)return;const[invoices,history,collection]=await Promise.all([supabase.from('v_invoice_balances').select('*').eq('workspace_id',workspaceId).gt('amount_due',0).order('due_date'),supabase.from('payment_reminders').select('invoice_id,reminder_level,status,reminder_date,late_fee_amount').eq('workspace_id',workspaceId),supabase.from('collection_referrals').select('invoice_id,status,recipient_email').eq('workspace_id',workspaceId)]);if(invoices.error)setMsg(invoices.error.message);else setRows((invoices.data||[])as Invoice[]);if(history.error)setMsg(history.error.message);else setReminders((history.data||[])as Reminder[]);if(collection.error)setMsg(collection.error.message);else setReferrals((collection.data||[])as Referral[])};
  useEffect(()=>{void load()},[workspaceId]);
  const pay=async(row:Invoice)=>{const amount=Number(prompt(`Payment amount (maximum ${row.amount_due})`,String(row.amount_due)));if(!amount)return;const{error}=await supabase.rpc('record_customer_payment',{p_invoice_id:row.invoice_id,p_payment_date:new Date().toISOString().slice(0,10),p_amount:amount,p_reference:null});if(error)setMsg(error.message);else{setMsg('Payment recorded.');void load()}};
  const escalate=async(row:Invoice,action:'reminder_1'|'reminder_2'|'collection')=>{let collection_recipient:string|null=null;if(action==='collection'){collection_recipient=prompt('Collection agency email address');if(!collection_recipient)return}const key=`${row.invoice_id}-${action}`;setBusy(key);setMsg(action==='collection'?'Sending collection package…':'Sending reminder…');const{data,error}=await supabase.functions.invoke('send-payment-escalation',{body:{invoice_id:row.invoice_id,action,collection_recipient}});setBusy('');if(error||data?.error)setMsg(data?.error||error?.message||'Could not send');else{setMsg(action==='collection'?`Collection package sent to ${data.recipient}.`:`Reminder ${data.level} sent to ${data.recipient}.`);void load()}};

  return <div><h1 className="text-3xl font-bold">Receivables</h1><p className="text-gray-600 mt-1 mb-6">Open invoice balances, payments and controlled reminder escalation.</p>{msg&&<p className="bg-blue-50 p-3 rounded mb-4">{msg}</p>}<div className="space-y-4">{rows.map(row=>{const first=reminders.find(item=>item.invoice_id===row.invoice_id&&item.reminder_level===1);const second=reminders.find(item=>item.invoice_id===row.invoice_id&&item.reminder_level===2);const referral=referrals.find(item=>item.invoice_id===row.invoice_id);return <div key={row.invoice_id} className="rounded-xl border bg-white p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{row.document_number}</p><p className={`text-sm ${row.is_overdue?'text-red-600':'text-gray-500'}`}>{row.is_overdue?'Overdue':'Due'} {row.due_date||'—'}</p></div><div className="sm:text-right"><p className="text-sm text-gray-500">Total {row.currency} {Number(row.total).toFixed(2)} · Paid {row.currency} {Number(row.amount_paid).toFixed(2)}</p><p className="font-semibold">Outstanding {row.currency} {Number(row.amount_due).toFixed(2)}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>pay(row)}>Record payment</Button>{row.is_overdue&&!first?.status.includes('sent')&&<Button size="sm" disabled={!!busy} onClick={()=>escalate(row,'reminder_1')}>{busy===`${row.invoice_id}-reminder_1`?'Sending…':'Send 1st reminder · no fee'}</Button>}{first?.status==='sent'&&!second?.status.includes('sent')&&<Button size="sm" disabled={!!busy} onClick={()=>escalate(row,'reminder_2')}>{busy===`${row.invoice_id}-reminder_2`?'Sending…':'Send 2nd reminder · 4% fee'}</Button>}{second?.status==='sent'&&referral?.status!=='sent'&&<Button size="sm" variant="danger" disabled={!!busy} onClick={()=>escalate(row,'collection')}>{busy===`${row.invoice_id}-collection`?'Sending…':'Collect through collection agency'}</Button>}</div><div className="mt-3 flex flex-wrap gap-2 text-xs text-gray-500">{first?.status==='sent'&&<span className="rounded bg-green-50 px-2 py-1 text-green-700">1st reminder sent {first.reminder_date}</span>}{second?.status==='sent'&&<span className="rounded bg-amber-50 px-2 py-1 text-amber-800">2nd reminder sent {second.reminder_date} · fee {row.currency} {Number(second.late_fee_amount).toFixed(2)}</span>}{referral?.status==='sent'&&<span className="rounded bg-red-50 px-2 py-1 text-red-700">Sent to collection: {referral.recipient_email}</span>}</div></div>})}{!rows.length&&<div className="rounded-xl border bg-white p-10 text-center text-gray-500">No open invoices.</div>}</div></div>;
}
