import{useEffect,useState}from'react';import{useApp}from'../contexts/AppContext';import{supabase}from'../lib/supabase';import{Button}from'../components/Button';import{Input}from'../components/Input';import{createSalesDocumentPdf,pdfBase64}from'../utils/salesDocumentPdf';
type Doc={id:string;document_type:string;document_number:string|null;issue_date:string;due_date:string|null;status:string;currency:string;subtotal:number;tax_total:number;total:number;amount_paid:number;issuer_snapshot:any;customer_snapshot:any;customer:any};type Line={id:string;description:string;quantity:number;unit:string;unit_price:number;net_amount:number;vat_amount:number;gross_amount:number};
export function SalesDocumentDetail({id}:{id:string}){const{workspace}=useApp();const[doc,setDoc]=useState<Doc|null>(null);const[lines,setLines]=useState<Line[]>([]);const[msg,setMsg]=useState('');const[fraction,setFraction]=useState('50');const[sending,setSending]=useState(false);
const load=async()=>{const{data,error}=await supabase.from('sales_documents').select('*,customer:counterparties(*)').eq('id',id).single();if(error)return setMsg(error.message);setDoc(data as Doc);const r=await supabase.from('sales_document_lines').select('*').eq('document_id',id).order('line_no');if(r.error)setMsg(r.error.message);else setLines((r.data||[])as Line[])};useEffect(()=>{void load()},[id]);
const rpc=async(name:string,args:any)=>{const{error}=await supabase.rpc(name,args);if(error)setMsg(error.message);else{setMsg('Saved.');void load()}};
const convert=()=>rpc('convert_quote_to_invoice',{p_quote_id:id,p_fraction:Number(fraction)/100,p_issue_date:new Date().toISOString().slice(0,10),p_due_date:null});
const makePdf=()=>doc?createSalesDocumentPdf(doc,lines,workspace?.legal_name||'Company'):null;
const pdf=()=>makePdf()?.save(`${doc?.document_number||'draft'}.pdf`);
const send=async()=>{const p=makePdf();if(!p||!doc)return;setSending(true);setMsg('Sending…');const{data,error}=await supabase.functions.invoke('send-sales-document',{body:{document_id:id,pdf_base64:pdfBase64(p),file_name:`${doc.document_number||'document'}.pdf`}});setSending(false);if(error||data?.error)setMsg(data?.error||error?.message||'Could not send email');else setMsg(`Sent to ${data.recipient}.`)};
if(!doc)return <p>{msg||'Loading…'}</p>;return <div className="max-w-5xl"><button className="text-sm text-blue-600 mb-4" onClick={()=>history.back()}>← Back</button><div className="bg-white border rounded-2xl p-7"><div className="flex justify-between"><div><p className="text-sm uppercase text-gray-500">{doc.document_type.replace('_',' ')}</p><h1 className="text-3xl font-bold">{doc.document_number||'Draft'}</h1><p className="text-gray-500 mt-1">{doc.customer?.company_name||doc.customer?.alias}</p></div><div className="text-right"><span className="capitalize bg-gray-100 px-3 py-1 rounded">{doc.status.replace('_',' ')}</span><p className="text-2xl font-bold mt-3">{doc.currency} {Number(doc.total).toFixed(2)}</p></div></div><table className="w-full mt-8"><thead className="text-left text-xs uppercase text-gray-500"><tr><th className="py-3">Description</th><th>Qty</th><th>Unit price</th><th>Tax</th><th className="text-right">Total</th></tr></thead><tbody>{lines.map(l=><tr key={l.id} className="border-t"><td className="py-3">{l.description}</td><td>{l.quantity} {l.unit}</td><td>{Number(l.unit_price).toFixed(2)}</td><td>{Number(l.vat_amount).toFixed(2)}</td><td className="text-right">{Number(l.gross_amount).toFixed(2)}</td></tr>)}</tbody></table><div className="flex flex-wrap justify-end gap-2 mt-7"><Button variant="secondary" onClick={pdf}>Download PDF</Button>{doc.status!=='draft'&&doc.status!=='void'&&<Button onClick={send} disabled={sending}>{sending?'Sending…':'Email PDF'}</Button>}{doc.status==='draft'&&<Button onClick={()=>rpc('issue_sales_document',{p_document_id:id})}>Issue document</Button>}{doc.document_type==='quote'&&doc.status==='sent'&&<Button onClick={()=>rpc('accept_quote',{p_quote_id:id})}>Accept quote</Button>}{doc.document_type==='quote'&&['accepted','partially_invoiced'].includes(doc.status)&&<div className="flex gap-2"><Input className="w-24" type="number" min="1" max="100" value={fraction} onChange={e=>setFraction(e.target.value)}/><Button onClick={convert}>Invoice %</Button></div>}</div>{msg&&<p className="text-sm text-amber-700 mt-4">{msg}</p>}</div></div>}
