import { useLanguage } from '../contexts/LanguageContext';

function navigate(path: string) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); }

export function SamlyLegal() {
  const { language } = useLanguage();
  const de = language === 'de';
  return <main className="min-h-screen bg-[#fbfaf8] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-3xl"><button onClick={() => navigate('/samly')} className="text-xl font-bold tracking-tight">samly<span className="text-blue-600">.</span></button><article className="mt-12 rounded-3xl border border-slate-200 bg-white p-6 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-700">{de ? 'RECHTLICHER HINWEIS' : 'LEGAL NOTICE'}</p><h1 className="mt-3 text-3xl font-bold tracking-tight">{de ? 'Samly ist ein Werkzeug, kein Steuerberater.' : 'Samly is a tool, not a tax adviser.'}</h1><div className="mt-7 space-y-5 leading-7 text-slate-700">{de ? <><p>Samly stellt Software zur Erfassung, Organisation und Auswertung von Buchhaltungsdaten bereit. Samly erbringt keine Steuer-, Rechts-, Wirtschaftsprüfungs- oder sonstige professionelle Beratung.</p><p>Du bleibst allein verantwortlich für die Richtigkeit, Vollständigkeit und rechtzeitige Prüfung aller Daten, Steuercodes, Rechnungen, Aufzeichnungen, Meldungen, Zahlungen und gesetzlichen Pflichten. Prüfe die Ergebnisse vor ihrer Verwendung und ziehe bei Bedarf qualifizierte steuerliche oder rechtliche Beratung hinzu.</p><p>Die länderspezifischen Einstellungen unterstützen derzeit Österreich und die Vereinigten Arabischen Emirate. Sie sind keine Zusage, dass eine konkrete Buchung, Rechnung oder Meldung rechtlich oder steuerlich korrekt ist.</p></> : <><p>Samly provides software for recording, organising and reporting accounting data. Samly does not provide tax, legal, audit, accounting or other professional advice.</p><p>You remain solely responsible for the accuracy, completeness and timely review of all data, tax codes, invoices, records, filings, payments and legal obligations. Review every result before use and obtain qualified tax or legal advice where needed.</p><p>Country-specific settings currently support Austria and the United Arab Emirates. They are not a representation that a particular booking, invoice or filing is legally or tax compliant.</p></>}</div><div className="mt-8 border-t border-slate-200 pt-6 text-sm leading-6 text-slate-600"><p>{de ? 'Offizielle Quellen:' : 'Official references:'}</p><ul className="mt-2 list-disc space-y-1 pl-5"><li><a className="text-blue-700 hover:underline" href="https://www.usp.gv.at/themen/steuern-finanzen/umsatzsteuer-ueberblick/rechnung.html" target="_blank" rel="noreferrer">Austria: invoice and VAT information</a></li><li><a className="text-blue-700 hover:underline" href="https://www.tax.gov.ae/en/taxes/Vat/vat.topics/tax.invoices.aspx" target="_blank" rel="noreferrer">UAE Federal Tax Authority: tax invoices</a></li></ul></div></article></div></main>;
}
