import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { useLanguage } from '../contexts/LanguageContext';
function navigate(path:string){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));}
const shell=(children:React.ReactNode)=><div className="relative min-h-screen overflow-hidden bg-slate-950"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,#2563eb_0%,transparent_28%),radial-gradient(circle_at_85%_80%,#0f766e_0%,transparent_24%)]"/><div className="relative mx-auto flex min-h-screen max-w-md flex-col justify-center p-5 sm:p-8">{children}</div></div>;
export function SamlyForgotPassword(){const{language}=useLanguage(),de=language==='de';const[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/samly/reset-password`});setBusy(false);setMessage(error?(de?`Der Reset-Link konnte nicht versendet werden: ${error.message}`:`We could not send the reset link: ${error.message}`):de?'Wenn ein Samly-Konto zu dieser Adresse existiert, ist der Link unterwegs.':'If a Samly account exists for that address, a reset link is on its way.')};return shell(<section className="rounded-3xl bg-white p-7 shadow-2xl"><button onClick={()=>navigate('/samly/login')} className="text-sm font-semibold text-blue-700">← {de?'Zurück zur Anmeldung':'Back to sign in'}</button><p className="mt-6 text-xs font-semibold uppercase tracking-[.18em] text-blue-700">{de?'PASSWORT':'PASSWORD'}</p><h1 className="mt-2 text-3xl font-bold">{de?'Wieder rein ins Konto.':'Let’s get you back in.'}</h1><p className="mt-3 text-slate-600">{de?'Kein Drama. Wir schicken dir einen sicheren Link zum Zurücksetzen.':'No paperwork required. We will send a secure reset link.'}</p><form onSubmit={submit} className="mt-6 space-y-4"><Input label={de?'E-Mail':'Email'} type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Button className="w-full" disabled={busy}>{busy?'…':de?'Reset-Link senden':'Send reset link'}</Button></form>{message&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}</section>)}
export function SamlyResetPassword(){const{language}=useLanguage(),de=language==='de';const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setReady(!!data.session);if(!data.session)setMessage(de?'Dieser Link ist ungültig oder abgelaufen.':'This link is invalid or has expired.');});const{subscriptions:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'&&session){setReady(true);setMessage('');}});return()=>subscription.unsubscribe();},[de]);const submit=async(e:FormEvent)=>{e.preventDefault();if(password.length<8)return setMessage(de?'Bitte verwende mindestens 8 Zeichen.':'Use at least 8 characters.');if(password!==confirm)return setMessage(de?'Die Passwörter stimmen nicht überein.':'The passwords do not match.');setBusy(true);const{error}=await supabase.auth.updateUser({password});setBusy(false);if(error)return setMessage(error.message);setMessage(de?'Passwort aktualisiert. Du kannst dich jetzt anmelden.':'Password updated. You can now sign in.');setTimeout(()=>navigate('/samly/login'),900)};return shell(<section className="rounded-3xl bg-white p-7 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-700">{de?'NEUES PASSWORT':'NEW PASSWORD'}</p><h1 className="mt-2 text-3xl font-bold">{de?'Neuer Schlüssel, weniger Chaos.':'New key, same calm books.'}</h1>{ready?<form onSubmit={submit} className="mt-6 space-y-4"><Input label={de?'Neues Passwort':'New password'} type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><Input label={de?'Passwort wiederholen':'Repeat password'} type="password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} required/><Button className="w-full" disabled={busy}>{busy?'…':de?'Passwort speichern':'Save password'}</Button></form>:<Button className="mt-6" onClick={()=>navigate('/samly/forgot-password')}>{de?'Neuen Link anfordern':'Request a new link'}</Button>}{message&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}</section>)}
