import { useLanguage } from '../contexts/LanguageContext';

type DocumentKey = 'notice' | 'terms' | 'eula' | 'privacy' | 'cancellation' | 'dpa' | 'tax';
const company = 'IACy International FZCO';
const address = 'Dubai Airport Free Zone, Building 9W, Block C, Office 523 - 68 9WC 523, Dubai, United Arab Emirates';
const legal = 'Private Freezone Limited Liability Company · Licence No. 05573 · Dubai Integrated Economic Zones Authority';
const contact = 'samly@iacy.com';
const euRepresentative = 'Nikolaus SKENE, Skodagasse 28/5, 1080 Vienna, Austria · ns@iacy.com';

function navigate(path: string) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); }
function selectDocument(key: DocumentKey) { navigate(`/samly/legal?document=${key}`); }

const titles: Record<DocumentKey, [string, string]> = {
  notice: ['Imprint', 'Legal notice'], terms: ['Allgemeine Geschäftsbedingungen', 'Terms of Service'], eula: ['Endnutzer-Lizenzvertrag', 'End User Licence Agreement'], privacy: ['Datenschutzerklärung', 'Privacy Policy'], cancellation: ['Kündigung', 'Cancellation Policy'], dpa: ['Auftragsverarbeitung', 'Data Processing Addendum'], tax: ['Hinweis zu Steuern & Buchhaltung', 'Tax & accounting notice'],
};

export function SamlyLegal() {
  const { language, setLanguage } = useLanguage();
  const de = language === 'de';
  const requested = new URLSearchParams(window.location.search).get('document') as DocumentKey | null;
  const document = requested && requested in titles ? requested : 'notice';
  const title = titles[document][de ? 0 : 1];
  const section = (heading: string, children: React.ReactNode) => <section className="mt-8"><h2 className="text-xl font-bold text-slate-900">{heading}</h2><div className="mt-3 space-y-3 leading-7 text-slate-700">{children}</div></section>;
  const details = <address className="not-italic leading-7 text-slate-700"><strong>{company}</strong><br/>{address}<br/>{legal}<br/>Company Manager: Nikolaus SKENE<br/><a className="font-semibold text-blue-700 hover:underline" href={`mailto:${contact}`}>{contact}</a> · <a className="font-semibold text-blue-700 hover:underline" href="tel:+971523888716">+971 52 388 8716</a></address>;

  const content: Record<DocumentKey, React.ReactNode> = de ? {
    notice: <>{section('Betreiber', <><p>Samly wird betrieben von:</p>{details}</>)}{section('EU-Vertreter für Datenschutz', <p>Für Angelegenheiten nach Art. 27 DSGVO ist unser EU-Vertreter: <strong>{euRepresentative}</strong>.</p>)}{section('Kontakt', <p>Fragen zu Samly, Verträgen oder Datenschutz: <a className="font-semibold text-blue-700 underline" href={`mailto:${contact}`}>{contact}</a>.</p>)}</>,
    terms: <>{section('1. Geltungsbereich und B2B-Nutzung', <p>Samly ist ein Online-Softwaredienst für Unternehmen und Selbständige. Mit der Registrierung bestätigst du, dass du Samly ausschließlich für deine gewerbliche oder berufliche Tätigkeit nutzt und berechtigt bist, dein Unternehmen an diese Bedingungen zu binden.</p>)}{section('2. Zugang und Verantwortung', <p>Du schützt deine Zugangsdaten, sorgst für korrekte Nutzerberechtigungen und bist für alle Inhalte, Buchungen, Rechnungen, Steuerkennzeichen und Handlungen in deinem Arbeitsbereich verantwortlich.</p>)}{section('3. Gebühren, Verlängerung und Kündigung', <p>Bezahlte Pläne verlängern sich automatisch jeweils für den gewählten Abrechnungszeitraum, sofern sie nicht vor der Verlängerung gekündigt werden. Du kannst jederzeit kündigen. Der Zugang bleibt bis zum Ende des bereits bezahlten Zeitraums aktiv. Bereits gezahlte Gebühren werden nicht zeitanteilig erstattet.</p>)}{section('4. Deine Daten', <p>Du behältst die Rechte an deinen Daten. Du erteilst uns die beschränkte Erlaubnis, sie zu hosten, zu sichern und zu verarbeiten, soweit dies zur Bereitstellung und Sicherheit von Samly erforderlich ist. Exportmöglichkeiten bleiben verfügbar, soweit dein Plan und gesetzliche Pflichten dies vorsehen.</p>)}{section('5. Zulässige Nutzung', <p>Du darfst Samly nicht rechtswidrig, missbräuchlich, zur Umgehung von Sicherheitsmaßnahmen oder zur Verarbeitung von Daten ohne die erforderliche Berechtigung nutzen.</p>)}{section('6. Verfügbarkeit und Haftung', <p>Samly wird mit angemessener Sorgfalt bereitgestellt. Gesetzlich zwingende Ansprüche bleiben unberührt. Im Übrigen besteht keine Zusage einer ununterbrochenen Verfügbarkeit oder eines bestimmten wirtschaftlichen, steuerlichen oder rechtlichen Ergebnisses.</p>)}{section('7. Änderungen', <p>Wir dürfen Funktionen und diese Bedingungen weiterentwickeln. Wesentliche Änderungen teilen wir rechtzeitig mit. Die weitere Nutzung nach Inkrafttreten gilt als Zustimmung, soweit rechtlich zulässig.</p>)}</>,
    eula: <>{section('1. Software-Lizenz', <p>Vorbehaltlich dieser Bedingungen erhältst du ein beschränktes, persönliches, widerrufliches, nicht übertragbares und nicht unterlizenzierbares Recht, Samly während eines aktiven Zugangs für deine interne gewerbliche oder berufliche Nutzung zu verwenden.</p>)}{section('2. Keine Zusage zur Richtigkeit', <p>Samly verarbeitet von dir bereitgestellte Daten und kann Vorschläge, Berechnungen, Klassifizierungen, Extraktionen und Berichte erzeugen. Diese Ergebnisse können unvollständig, verspätet oder fehlerhaft sein. Sie sind keine Steuer-, Rechts-, Buchhaltungs-, Prüfungs- oder Unternehmensberatung und keine Zusage, dass Daten, Buchungen, Rechnungen, Steuerkennzeichen, Meldungen oder Berechnungen richtig, vollständig oder rechtskonform sind.</p>)}{section('3. Deine Prüfungspflicht', <p>Du prüfst und freigibst jede Eingabe und jedes Ergebnis vor Nutzung, Buchung, Abgabe, Zahlung oder Weitergabe. Du bleibst allein verantwortlich für steuerliche Erklärungen, gesetzliche Fristen, Rechnungen, Aufzeichnungen, Zahlungen, Zugriffsrechte und die Einholung professioneller Beratung.</p>)}{section('4. Keine Gewährleistung', <p>Samly wird im gesetzlich zulässigen Umfang ohne ausdrückliche oder stillschweigende Gewährleistung bereitgestellt. Wir garantieren weder eine ununterbrochene oder fehlerfreie Verfügbarkeit noch bestimmte Ergebnisse oder die Kompatibilität mit jeder externen Bank, E-Mail-, Steuer- oder Drittanbieter-Schnittstelle.</p>)}{section('5. Haftungsbegrenzung', <p>Soweit gesetzlich zulässig, haften IACy International FZCO, ihre Organe, Mitarbeitenden und Erfüllungsgehilfen nicht für mittelbare Schäden, Folgeschäden, entgangenen Gewinn, Datenverlust, Steuerzahlungen, Strafen, Zinsen oder Ansprüche Dritter, die aus der Nutzung oder Nichtnutzung von Samly oder einem Ergebnis daraus entstehen. Soweit eine Haftung nicht ausgeschlossen werden kann, ist sie auf die von dir für Samly in den zwölf Monaten vor dem Ereignis gezahlten Gebühren begrenzt. Zwingende gesetzliche Haftung, insbesondere für Vorsatz oder Fälle, in denen ein Ausschluss rechtlich unzulässig ist, bleibt unberührt.</p>)}{section('6. Sperrung und Beendigung', <p>Wir dürfen den Zugang bei Sicherheitsrisiken, Zahlungsverzug, rechtswidriger Nutzung oder einem erheblichen Verstoß gegen diese EULA vorübergehend sperren oder beenden. Deine Pflichten zu offenen Gebühren und zur rechtmäßigen Datenverarbeitung bleiben bestehen.</p>)}</>,
    privacy: <>{section('Verantwortlicher', <>{details}<p>EU-Vertreter: <strong>{euRepresentative}</strong>.</p></>)}{section('Welche Daten wir verarbeiten', <p>Wir verarbeiten Kontodaten, Kontakt- und Unternehmensdaten, Rechnungen, Belege und andere Inhalte, die du hochlädst oder per E-Mail weiterleitest, Nutzungs- und Sicherheitsdaten, Support-Anfragen sowie Stripe-Zahlungs- und Abonnementdaten.</p>)}{section('Zwecke und Rechtsgrundlagen', <p>Wir verarbeiten Daten zur Bereitstellung und Sicherung des Vertrags, zur Abrechnung, für Support, zur Betrugsprävention sowie zur Erfüllung rechtlicher Pflichten. Soweit erforderlich, stützen wir die Verarbeitung auf Vertragserfüllung, berechtigte Interessen oder gesetzliche Pflichten.</p>)}{section('Empfänger und internationale Übermittlungen', <p>Wir nutzen sorgfältig ausgewählte Dienstleister für Hosting und Datenbank (Supabase), Hosting (Netlify), Zahlungen (Stripe), E-Mail (Postmark) sowie, wenn aktiviert, KI-gestützte Dokumentextraktion (OpenAI). Diese Dienstleister verarbeiten Daten nur soweit nötig. Bei Übermittlungen außerhalb des EWR nutzen wir geeignete Schutzmaßnahmen, soweit erforderlich.</p>)}{section('Speicherdauer und deine Rechte', <p>Wir speichern personenbezogene Daten nur solange sie für den Dienst, gesetzliche Aufbewahrungspflichten oder die Abwehr bzw. Durchsetzung von Ansprüchen erforderlich sind. Du kannst Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch und Datenübertragbarkeit beantragen. Schreibe an {contact}. Du kannst dich auch bei einer zuständigen Datenschutzaufsicht beschweren.</p>)}{section('Technisch notwendige Speicherung', <p>Samly verwendet notwendige lokale Browser-Speicher für Sitzung, Sprache und wesentliche Produktfunktionen. Wir setzen keine Werbe- oder Marketing-Cookies ein.</p>)}</>,
    cancellation: <>{section('Kündigung', <p>Du kannst deinen bezahlten Samly-Plan jederzeit in der Abrechnung kündigen. Die Kündigung beendet die automatische Verlängerung.</p>)}{section('Wirksamkeit', <p>Dein Zugang bleibt bis zum Ende des bereits bezahlten monatlichen oder jährlichen Abrechnungszeitraums aktiv.</p>)}{section('Erstattungen', <p>Bereits gezahlte Gebühren werden nicht zeitanteilig erstattet. Gesetzlich zwingende Ansprüche bleiben unberührt.</p>)}{section('Daten', <p>Exportiere wichtige Unterlagen und Berichte vor Ablauf deines Zugangs. Gesetzliche Aufbewahrungspflichten und vereinbarte Löschfristen bleiben unberührt.</p>)}</>,
    dpa: <>{section('Rollen', <p>Soweit du personenbezogene Daten deiner Kunden, Lieferanten oder Mitarbeitenden in Samly verarbeitest, bist du Verantwortlicher und IACy International FZCO verarbeitet diese Daten als Auftragsverarbeiter ausschließlich zur Bereitstellung und Sicherung der vereinbarten Samly-Dienste.</p>)}{section('Weisungen und Vertraulichkeit', <p>Wir verarbeiten personenbezogene Daten nur auf deine dokumentierten Weisungen, soweit nicht geltendes Recht etwas anderes verlangt. Personen mit Zugriff auf die Daten sind zur Vertraulichkeit verpflichtet.</p>)}{section('Sicherheit und Unterauftragsverarbeiter', <p>Wir treffen angemessene technische und organisatorische Maßnahmen. Wir setzen Unterauftragsverarbeiter ein, darunter Supabase, Netlify, Stripe, Postmark und bei aktivierter Extraktion OpenAI. Wir bleiben für deren Auswahl und vertragliche Verpflichtung verantwortlich.</p>)}{section('Unterstützung, Löschung und Übermittlungen', <p>Wir unterstützen dich angemessen bei Betroffenenrechten und Sicherheitsvorfällen. Nach Ende des Dienstes werden Daten nach unseren dokumentierten Lösch- und Aufbewahrungsprozessen gelöscht oder zurückgegeben, sofern keine gesetzliche Pflicht zur Aufbewahrung besteht. Für Übermittlungen außerhalb des EWR gelten erforderlichenfalls geeignete Schutzmaßnahmen.</p>)}</>,
    tax: <>{section('Samly ist ein Werkzeug, kein Steuerberater.', <><p>Samly stellt Software zur Erfassung, Organisation und Auswertung von Buchhaltungsdaten bereit. Samly erbringt keine Steuer-, Rechts-, Wirtschaftsprüfungs- oder sonstige professionelle Beratung.</p><p>Du bleibst allein verantwortlich für die Richtigkeit, Vollständigkeit und rechtzeitige Prüfung aller Daten, Steuercodes, Rechnungen, Aufzeichnungen, Meldungen, Zahlungen und gesetzlichen Pflichten. Prüfe jedes Ergebnis vor seiner Verwendung und hole bei Bedarf qualifizierte steuerliche oder rechtliche Beratung ein.</p><p>Die länderspezifischen Einstellungen unterstützen derzeit Österreich und die Vereinigten Arabischen Emirate. Sie sind keine Zusage, dass eine konkrete Buchung, Rechnung oder Meldung rechtlich oder steuerlich korrekt ist.</p></>)}</>,
  } : {
    notice: <>{section('Operator', <><p>Samly is operated by:</p>{details}</>)}{section('EU data-protection representative', <p>For matters under GDPR Article 27, our EU representative is <strong>{euRepresentative}</strong>.</p>)}{section('Contact', <p>Questions about Samly, contracts or privacy: <a className="font-semibold text-blue-700 underline" href={`mailto:${contact}`}>{contact}</a>.</p>)}</>,
    terms: <>{section('1. Scope and B2B use', <p>Samly is online software for businesses and self-employed professionals. By registering, you confirm that you use Samly solely for commercial or professional purposes and have authority to bind your business to these terms.</p>)}{section('2. Access and responsibility', <p>You protect your login credentials, manage user access correctly, and remain responsible for every item of content, booking, invoice, tax code and action in your workspace.</p>)}{section('3. Fees, renewal and cancellation', <p>Paid plans renew automatically for the selected billing period unless cancelled before renewal. You may cancel at any time. Access stays active until the end of the already-paid period. Fees already paid are not refunded pro rata.</p>)}{section('4. Your data', <p>You retain rights in your data. You grant us the limited permission to host, secure and process it as needed to provide and protect Samly. Export remains available where your plan and legal obligations allow.</p>)}{section('5. Acceptable use', <p>You may not use Samly unlawfully, abusively, to bypass security measures, or to process data without the required authority.</p>)}{section('6. Availability and liability', <p>Samly is provided with reasonable care. Mandatory legal rights remain unaffected. Otherwise, we do not promise uninterrupted availability or any particular commercial, tax or legal outcome.</p>)}{section('7. Changes', <p>We may improve features and these terms. We will give reasonable notice of material changes. Continued use after an effective change means acceptance where permitted by law.</p>)}</>,
    eula: <>{section('1. Software licence', <p>Subject to these terms, you receive a limited, personal, revocable, non-transferable and non-sublicensable right to use Samly during active access for your internal business or professional use.</p>)}{section('2. No promise of accuracy', <p>Samly processes data you provide and may generate suggestions, calculations, classifications, extractions and reports. These outputs may be incomplete, delayed or incorrect. They are not tax, legal, accounting, audit or business advice, and are not a representation that any data, booking, invoice, tax code, filing or calculation is accurate, complete or compliant.</p>)}{section('3. Your review duty', <p>You review and approve every input and output before using, booking, filing, paying or sharing it. You remain solely responsible for tax filings, legal deadlines, invoices, records, payments, access rights and obtaining professional advice.</p>)}{section('4. No warranty', <p>To the fullest extent permitted by law, Samly is provided without express or implied warranties. We do not guarantee uninterrupted or error-free availability, a particular result, or compatibility with every external bank, email, tax or third-party integration.</p>)}{section('5. Limitation of liability', <p>To the fullest extent permitted by law, IACy International FZCO, its officers, employees and suppliers are not liable for indirect or consequential loss, lost profits, data loss, tax liabilities, penalties, interest or third-party claims arising from Samly, its use, non-use or any output. Where liability cannot be excluded, it is limited to the fees you paid for Samly in the twelve months before the event. Mandatory liability, including intentional misconduct or any liability that cannot lawfully be excluded, remains unaffected.</p>)}{section('6. Suspension and termination', <p>We may suspend or terminate access for a security risk, overdue payment, unlawful use or material breach of this EULA. Your duties regarding unpaid fees and lawful data processing continue.</p>)}</>,
    privacy: <>{section('Controller', <>{details}<p>EU representative: <strong>{euRepresentative}</strong>.</p></>)}{section('Personal data we process', <p>We process account, contact and company data; invoices, receipts and other content you upload or forward by email; usage and security data; support requests; and Stripe payment and subscription data.</p>)}{section('Purposes and legal bases', <p>We process data to provide and secure the service, handle billing and support, prevent fraud, and meet legal obligations. Where required, our legal bases are contract performance, legitimate interests or legal obligations.</p>)}{section('Recipients and international transfers', <p>We use carefully selected service providers for database and hosting (Supabase), web hosting (Netlify), payments (Stripe), email (Postmark), and, when enabled, AI-assisted document extraction (OpenAI). They process data only as needed for their service. Where data leaves the EEA, we use appropriate safeguards where required.</p>)}{section('Retention and your rights', <p>We retain personal data only for as long as needed for the service, legal retention duties, or the establishment, exercise or defence of legal claims. You may request access, correction, deletion, restriction, objection and data portability by writing to {contact}. You may also complain to a competent data-protection authority.</p>)}{section('Strictly necessary browser storage', <p>Samly uses necessary local browser storage for session, language and essential product features. We do not use advertising or marketing cookies.</p>)}</>,
    cancellation: <>{section('Cancellation', <p>You may cancel a paid Samly plan at any time in billing. Cancellation stops automatic renewal.</p>)}{section('Effective date', <p>Your access remains active until the end of the monthly or annual billing period already paid for.</p>)}{section('Refunds', <p>Fees already paid are not refunded pro rata. Mandatory legal rights remain unaffected.</p>)}{section('Data', <p>Export important records and reports before access ends. Legal retention duties and agreed deletion schedules remain unaffected.</p>)}</>,
    dpa: <>{section('Roles', <p>Where you process personal data of your customers, suppliers or personnel in Samly, you are the controller and IACy International FZCO processes that personal data as processor solely to provide and secure the agreed Samly services.</p>)}{section('Instructions and confidentiality', <p>We process personal data only on your documented instructions unless applicable law requires otherwise. Persons with access are bound by confidentiality.</p>)}{section('Security and sub-processors', <p>We apply appropriate technical and organisational measures. We use sub-processors including Supabase, Netlify, Stripe, Postmark and, when extraction is enabled, OpenAI. We remain responsible for their careful selection and contractual commitment.</p>)}{section('Assistance, deletion and transfers', <p>We reasonably assist with data-subject requests and security incidents. When the service ends, data is deleted or returned under our documented deletion and retention processes unless law requires retention. Appropriate safeguards apply where required for transfers outside the EEA.</p>)}</>,
    tax: <>{section('Samly is a tool, not a tax adviser.', <><p>Samly provides software for recording, organising and reporting accounting data. Samly does not provide tax, legal, audit, accounting or other professional advice.</p><p>You remain solely responsible for the accuracy, completeness and timely review of all data, tax codes, invoices, records, filings, payments and legal obligations. Review every result before use and obtain qualified tax or legal advice where needed.</p><p>Country-specific settings currently support Austria and the United Arab Emirates. They are not a representation that a particular booking, invoice or filing is legally or tax compliant.</p></>)}</>,
  };

  return <main className="min-h-screen bg-[#fbfaf8] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-4xl"><header className="flex flex-wrap items-center justify-between gap-4"><button onClick={() => navigate('/samly')} className="text-xl font-bold tracking-tight">samly<span className="text-blue-600">.</span></button><button onClick={() => setLanguage(de ? 'en' : 'de')} className="rounded-full border border-slate-200 px-3 py-2 text-sm font-semibold hover:bg-white">{de ? 'EN' : 'DE'}</button></header><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{(Object.keys(titles) as DocumentKey[]).map(key => <button key={key} onClick={() => selectDocument(key)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${document === key ? 'bg-slate-950 text-white' : 'border border-slate-200 bg-white text-slate-700 hover:border-blue-300'}`}>{titles[key][de ? 0 : 1]}</button>)}</div><article className="mt-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-700">SAMLY · {de ? 'STAND' : 'EFFECTIVE'} 20 {de ? 'SEPTEMBER' : 'SEPTEMBER'} 2026</p><h1 className="mt-3 text-3xl font-bold tracking-tight">{title}</h1>{content[document]}</article></div></main>;
}
