import { useEffect, useState } from 'react';
import { useApp } from '../contexts/AppContext';
import { supabase } from '../lib/supabase';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { Select } from '../components/Select';

type Statement={id:string;bank_account_id:string;institution_name:string;statement_from:string|null;statement_to:string|null;opening_balance:number|null;closing_balance:number|null;currency:string;file_name:string;file_path:string;status:string;extraction_method:string;extraction_error:string|null};
type Row={id:string;row_order:number;booked_date:string|null;value_date:string|null;description:string|null;counterparty:string|null;reference:string|null;amount:number|null;currency:string|null;confidence:number|null;review_status:string;classification:string};
type Bank={id:string;name:string};

async function fileHash(file:File){const value=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return Array.from(new Uint8Array(value)).map(x=>x.toString(16).padStart(2,'0')).join('')}

export function StatementImports(){
 const{workspaceId,workspace}=useApp();const[statements,setStatements]=useState<Statement[]>([]);const[banks,setBanks]=useState<Bank[]>([]);const[selected,setSelected]=useState<Statement|null>(null);const[rows,setRows]=useState<Row[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[file,setFile]=useState<File|null>(null);const[form,setForm]=useState({bank_account_id:'',institution_name:'Bank Austria',account_role:'bank'});
 const load=async()=>{if(!workspaceId)return;const[{data:s,error},{data:b}]=await Promise.all([supabase.from('bank_statement_imports').select('*').eq('workspace_id',workspaceId).order('created_at',{ascending:false}),supabase.from('bank_accounts').select('id,name').eq('workspace_id',workspaceId).eq('is_active',true)]);if(error)setMsg(error.message);else setStatements((s||[])as Statement[]);setBanks((b||[])as Bank[]);if(!form.bank_account_id&&b?.[0])setForm(x=>({...x,bank_account_id:b[0].id}))};
 useEffect(()=>{void load()},[workspaceId]);
 const open=async(statement:Statement)=>{setSelected(statement);const{data,error}=await supabase.from('bank_statement_rows').select('*').eq('statement_import_id',statement.id).order('row_order');setRows((data||[])as Row[]);if(error)setMsg(error.message)};
 const upload=async()=>{if(!file||!workspaceId||!form.bank_account_id)return;setBusy(true);setMsg('Uploading original statement…');try{const hash=await fileHash(file);const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${workspaceId}/bank-statements/${Date.now()}-${safe}`;const{error:uploadError}=await supabase.storage.from('finance-documents').upload(path,file,{contentType:file.type||'application/pdf',upsert:false});if(uploadError)throw uploadError;const{data:user}=await supabase.auth.getUser();const{data:record,error}=await supabase.from('bank_statement_imports').insert({workspace_id:workspaceId,bank_account_id:form.bank_account_id,account_role:form.account_role,institution_name:form.institution_name,currency:workspace?.base_currency||'EUR',file_name:file.name,file_path:path,file_sha256:hash,created_by:user.user?.id}).select('*').single();if(error){await supabase.storage.from('finance-documents').remove([path]);throw error}setMsg('Uploaded. Starting extraction…');const{error:fnError}=await supabase.functions.invoke('extract-bank-statement',{body:{import_id:record.id}});if(fnError)setMsg(`Upload is safe, but extraction is not configured yet: ${fnError.message}`);else setMsg('Extraction complete. Review every row before importing.');setFile(null);await load();await open(record as Statement)}catch(error:any){setMsg(error.message)}finally{setBusy(false)}};
 const updateRow=async(row:Row,changes:Partial<Row>)=>{const next={...row,...changes};setRows(x=>x.map(r=>r.id===row.id?next:r));const{error}=await supabase.from('bank_statement_rows').update(changes).eq('id',row.id);if(error)setMsg(error.message)};
 const reconcile=async()=>{if(!selected)return;const{data,error}=await supabase.rpc('reconcile_bank_statement',{p_import_id:selected.id});setMsg(error?error.message:data.reconciled?'Statement balances reconcile. It is ready to import.':`Review needed: balance difference ${data.balance_delta}, proposed rows ${data.unreviewed_rows}.`);if(!error)setSelected({...selected,status:data.reconciled?'reconciled':'needs_review'});await load()};
 const importRows=async()=>{if(!selected)return;setBusy(true);const{data,error}=await supabase.rpc('import_reconciled_bank_statement',{p_import_id:selected.id});setMsg(error?error.message:`Imported ${data.rows_imported} reviewed rows into the bank inbox.`);setBusy(false);await load()};
 if(selected)return <div><button className="text-blue-600 mb-4" onClick={()=>setSelected(null)}>← All statements</button><div className="flex justify-between gap-4"><div><h1 className="text-3xl font-bold">{selected.file_name}</h1><p className="text-gray-600">{selected.institution_name} · {selected.statement_from||'unknown'} to {selected.statement_to||'unknown'}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={reconcile}>Check balance</Button><Button disabled={busy||selected.status!=='reconciled'} onClick={importRows}>Import approved rows</Button></div></div>{msg&&<p className="my-4 bg-blue-50 p-3 rounded">{msg}</p>}<div className="mt-5 bg-white border rounded-xl overflow-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">Date</th><th>Description</th><th>Counterparty</th><th>Amount</th><th>Type</th><th>Review</th><th>Confidence</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-2"><input type="date" className="border rounded p-1" value={r.booked_date||''} onChange={e=>updateRow(r,{booked_date:e.target.value||null,review_status:'corrected'})}/></td><td><input className="border rounded p-1 w-full" value={r.description||''} onChange={e=>updateRow(r,{description:e.target.value,review_status:'corrected'})}/></td><td><input className="border rounded p-1 w-full" value={r.counterparty||''} onChange={e=>updateRow(r,{counterparty:e.target.value,review_status:'corrected'})}/></td><td><input type="number" step="0.01" className="border rounded p-1 w-28" value={r.amount??''} onChange={e=>updateRow(r,{amount:e.target.value===''?null:Number(e.target.value),review_status:'corrected'})}/></td><td><select className="border rounded p-1" value={r.classification} onChange={e=>updateRow(r,{classification:e.target.value})}><option value="unknown">Unknown</option><option value="business">Business</option><option value="private">Private</option><option value="internal_transfer">Internal transfer</option><option value="card_settlement">Card settlement</option></select></td><td><select className="border rounded p-1" value={r.review_status} onChange={e=>updateRow(r,{review_status:e.target.value})}><option value="proposed">Needs review</option><option value="approved">Approved</option><option value="corrected">Corrected</option><option value="ignored">Ignore</option></select></td><td>{r.confidence==null?'—':`${Math.round(r.confidence*100)}%`}</td></tr>)}</tbody></table></div></div>;
 return <div><h1 className="text-3xl font-bold">Bank statement import</h1><p className="text-gray-600 mt-1">Original evidence → extraction proposal → human review → balance check → bank inbox.</p><div className="bg-white border rounded-xl p-5 my-6 grid md:grid-cols-4 gap-4 items-end"><Select label="Account" value={form.bank_account_id} onChange={e=>setForm({...form,bank_account_id:e.target.value})}>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Select label="Treatment" value={form.account_role} onChange={e=>setForm({...form,account_role:e.target.value})}><option value="bank">Bank</option><option value="credit_card">Credit card</option><option value="clearing">Clearing</option></Select><Input label="Institution" value={form.institution_name} onChange={e=>setForm({...form,institution_name:e.target.value})}/><div><label className="block text-sm font-medium mb-1">PDF statement</label><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="text-sm w-full"/></div><Button disabled={busy||!file||!form.bank_account_id} onClick={upload}>{busy?'Working…':'Upload and extract'}</Button></div>{msg&&<p className="my-4 bg-blue-50 p-3 rounded">{msg}</p>}<div className="bg-white border rounded-xl overflow-hidden"><table className="w-full"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="p-4">Institution</th><th>Period</th><th>Status</th><th>Method</th><th>File</th></tr></thead><tbody>{statements.map(s=><tr key={s.id} onClick={()=>open(s)} className="border-t hover:bg-blue-50 cursor-pointer"><td className="p-4">{s.institution_name}</td><td>{s.statement_from||'—'} – {s.statement_to||'—'}</td><td>{s.status}</td><td>{s.extraction_method}</td><td>{s.file_name}</td></tr>)}{!statements.length&&<tr><td colSpan={5} className="p-10 text-center text-gray-500">No statements uploaded.</td></tr>}</tbody></table></div></div>;
}
