import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const env=(name:string)=>{const value=Deno.env.get(name);if(!value)throw new Error(`${name} is not configured`);return value;};
const timingSafe=(a:string,b:string)=>{if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;};
const hex=async(value:string,secret:string)=>Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const verify=async(body:string,header:string|null)=>{if(!header)throw new Error('Missing Stripe signature');const values=Object.fromEntries(header.split(',').map(part=>part.split('=')));const timestamp=Number(values.t);const signatures=header.split(',').filter(part=>part.startsWith('v1=')).map(part=>part.slice(3));if(!Number.isFinite(timestamp)||Math.abs(Date.now()/1000-timestamp)>300)throw new Error('Expired Stripe signature');const expected=await hex(`${timestamp}.${body}`,env('STRIPE_WEBHOOK_SECRET'));if(!signatures.some(signature=>timingSafe(signature,expected)))throw new Error('Invalid Stripe signature');};
const status=(value:string)=>['trialing','active','past_due','cancelled','unpaid'].includes(value)?value:'pending';
Deno.serve(async req=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});try{const body=await req.text();await verify(body,req.headers.get('stripe-signature'));const event=JSON.parse(body);const db=createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'));const {error:seen}=await db.from('samly_stripe_events').insert({stripe_event_id:event.id,event_type:event.type,payload:event});if(seen?.code==='23505')return new Response(JSON.stringify({received:true,duplicate:true}),{headers:{'Content-Type':'application/json'}});if(seen)throw seen;
 const object=event.data?.object||{};const accountId=object.metadata?.account_id;let account=accountId?{id:accountId}:null;if(!account&&object.customer){const {data}=await db.from('samly_accounts').select('id').eq('stripe_customer_id',object.customer).maybeSingle();account=data;}if(!account)return new Response(JSON.stringify({received:true,unmatched:true}),{headers:{'Content-Type':'application/json'}});
 const price=object.items?.data?.[0]?.price?.id;const plan=object.metadata?.plan==='monthly'||object.metadata?.plan==='annual'?object.metadata.plan:price===env('SAMLY_STRIPE_MONTHLY_PRICE_ID')?'monthly':price===env('SAMLY_STRIPE_ANNUAL_PRICE_ID')?'annual':null;
 if(event.type==='checkout.session.completed'||event.type.startsWith('customer.subscription.')){const subscription=event.type==='checkout.session.completed'?object.subscription:object.id;const customer=event.type==='checkout.session.completed'?object.customer:object.customer;await db.from('samly_accounts').update({stripe_customer_id:customer||null,stripe_subscription_id:subscription||null,...(plan?{plan_code:plan}:{}),subscription_status:event.type==='checkout.session.completed'?'active':status(object.status),subscription_current_period_end:object.current_period_end?new Date(object.current_period_end*1000).toISOString():null,updated_at:new Date().toISOString()}).eq('id',account.id);}
 if(event.type==='invoice.payment_failed')await db.from('samly_accounts').update({subscription_status:'past_due',updated_at:new Date().toISOString()}).eq('id',account.id);return new Response(JSON.stringify({received:true}),{headers:{'Content-Type':'application/json'}});
 }catch(error){console.error(error);return new Response(JSON.stringify({error:error instanceof Error?error.message:'Webhook failed'}),{status:400,headers:{'Content-Type':'application/json'}})}});
