import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

type Address={Email?:string;Name?:string};
type Attachment={Name?:string;ContentType?:string;ContentLength?:number;Content?:string};
type Payload={MessageID?:string;From?:string;FromFull?:Address;Subject?:string;Date?:string;TextBody?:string;OriginalRecipient?:string;To?:string;ToFull?:Address[];CcFull?:Address[];BccFull?:Address[];Headers?:{Name?:string;Value?:string}[];Attachments?:Attachment[]};
const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'');
const secret=()=>{const value=Deno.env.get('SAMLY_POSTMARK_INBOUND_SECRET');if(!value)throw new Error('SAMLY_POSTMARK_INBOUND_SECRET is not configured');return value;};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const email=(value:unknown)=>typeof value==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim())?value.trim().toLowerCase():'';
const safe=(value:unknown)=>typeof value==='string'?value.replace(/[\\/\x00-\x1f]/g,'_').slice(0,240)||'attachment':'attachment';
const mime=(value:unknown)=>typeof value==='string'?value.toLowerCase().split(';')[0].trim():'application/octet-stream';
const allowed=new Set(['application/pdf','image/jpeg','image/png','image/heic','text/plain']);
async function sha(bytes:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(byte=>byte.toString(16).padStart(2,'0')).join('');}
function recipients(p:Payload){return [p.OriginalRecipient,...(p.BccFull||[]).map(a=>a.Email),...(p.ToFull||[]).map(a=>a.Email),...(p.CcFull||[]).map(a=>a.Email),p.To].map(email).filter(Boolean);}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'POST required'},405);try{
 const expected=`Basic ${btoa(`samly:${secret()}`)}`;if(req.headers.get('authorization')!==expected)return json({error:'Unauthorized'},401);
 const payload=await req.json() as Payload;const targets=recipients(payload);if(!targets.length)return json({received:true,ignored:true});
 const {data:alias,error:aliasError}=await db.from('receipt_aliases').select('alias,workspace_id,mailbox_id,receipt_mailboxes!inner(id,provider,enabled)').in('alias',targets).eq('receipt_mailboxes.provider','postmark_inbound').eq('receipt_mailboxes.enabled',true).maybeSingle();if(aliasError)throw aliasError;if(!alias)return json({received:true,ignored:true});
 const messageId=typeof payload.MessageID==='string'&&payload.MessageID.trim()?payload.MessageID.trim().slice(0,500):crypto.randomUUID();const graphId=`postmark:${messageId}`;
 const sender=email(payload.FromFull?.Email||payload.From);const receivedAt=typeof payload.Date==='string'&&Number.isFinite(Date.parse(payload.Date))?new Date(payload.Date).toISOString():new Date().toISOString();
 const {data:source,error:sourceError}=await db.from('receipt_emails').upsert({mailbox_id:alias.mailbox_id,graph_id:graphId,internet_message_id:messageId,sender:sender||null,subject:typeof payload.Subject==='string'?payload.Subject.slice(0,500):null,received_at:receivedAt,recipients:targets,headers:payload.Headers||[],body_text:typeof payload.TextBody==='string'?payload.TextBody.slice(0,100000):'',status:'received'},{onConflict:'mailbox_id,graph_id',ignoreDuplicates:true}).select('id,status').maybeSingle();if(sourceError)throw sourceError;
 if(!source)return json({received:true,duplicate:true});if(source.status==='processed')return json({received:true,duplicate:true});
 let documents=0;for(let index=0;index<(payload.Attachments||[]).length;index++){const item=(payload.Attachments||[])[index];const type=mime(item.ContentType);const name=safe(item.Name);if(!allowed.has(type)||!item.Content){continue;}const bytes=Uint8Array.from(atob(item.Content),char=>char.charCodeAt(0));if(bytes.length>20*1024*1024)continue;documents++;const id=crypto.randomUUID();const {error:insertError}=await db.from('receipt_candidates').insert({id,email_id:source.id,source_key:`postmark:${index}`,workspace_id:alias.workspace_id,receiving_alias:alias.alias,entity_evidence:{provider:'postmark',recipient:alias.alias,message_id:messageId},filename:name,mime_type:type});if(insertError){if((insertError as {code?:string}).code==='23505')continue;throw insertError;}const path=`${id}/original`;const store=await db.storage.from('receipt-originals').upload(path,bytes,{contentType:type,upsert:false});if(store.error)throw store.error;const hash=await sha(bytes);const {data:duplicate}=await db.from('receipt_candidates').select('id').eq('file_hash',hash).neq('id',id).not('file_path','is',null).limit(1).maybeSingle();const {error:updateError}=await db.from('receipt_candidates').update({file_path:path,file_hash:hash,...(duplicate?{status:'duplicate',duplicate_status:'confirmed_duplicate',duplicate_of:duplicate.id}:{})}).eq('id',id);if(updateError)throw updateError;await db.from('receipt_processing_events').insert({receipt_id:id,event:duplicate?'duplicate_detected':'postmark_attachment_received',details:{message_id:messageId}});}
 if(!documents&&typeof payload.TextBody==='string'&&payload.TextBody.trim()){const id=crypto.randomUUID();const {error:insertError}=await db.from('receipt_candidates').insert({id,email_id:source.id,source_key:'postmark:body',workspace_id:alias.workspace_id,receiving_alias:alias.alias,entity_evidence:{provider:'postmark',recipient:alias.alias,message_id:messageId},filename:'email-body.txt',mime_type:'text/plain'});if(!insertError){const path=`${id}/original`;const store=await db.storage.from('receipt-originals').upload(path,payload.TextBody,{contentType:'text/plain',upsert:false});if(store.error)throw store.error;await db.from('receipt_candidates').update({file_path:path}).eq('id',id);}}
 await db.from('receipt_emails').update({status:'processed',attempts:1,error:null}).eq('id',source.id);return json({received:true,queued:documents});
 }catch(error){console.error(error);return json({error:error instanceof Error?error.message:'Inbound processing failed'},500);}});
