import { FormEvent, useEffect, useRef, useState } from 'react';
import { Bug } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Button } from './Button';
import { Input } from './Input';
import { Modal } from './Modal';

type Capture = { blob: Blob; type: 'image/png' | 'image/jpeg' } | null;

export function SamlyBugReport(){
  const [enabled,setEnabled]=useState(true),[ready,setReady]=useState(false),[open,setOpen]=useState(false),[capturing,setCapturing]=useState(false),[capture,setCapture]=useState<Capture>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const userId=useRef<string | null>(null);
  useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; userId.current=user.id; const{data}=await supabase.from('samly_user_preferences').select('bug_reporting_enabled').eq('user_id',user.id).maybeSingle(); setEnabled(data?.bug_reporting_enabled ?? true); setReady(true);})();},[]);
  const openReport=async()=>{setMessage('');setCapture(null);setCapturing(true);try{const html2canvas=(await import('html2canvas')).default;const target=document.querySelector('main')||document.body;const canvas=await html2canvas(target as HTMLElement,{useCORS:true,backgroundColor:'#f9fafb',scale:Math.min(window.devicePixelRatio||1,2),windowWidth:window.innerWidth,windowHeight:window.innerHeight});const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(blob)setCapture({blob,type:'image/jpeg'});}catch{ /* A report can still be sent if a page cannot be captured. */ }finally{setCapturing(false);setOpen(true);}};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!userId.current)return;setBusy(true);setMessage('');try{let screenshotPath:string|undefined;if(capture){screenshotPath=`${userId.current}/${Date.now()}-${crypto.randomUUID()}.jpg`;const {error:uploadError}=await supabase.storage.from('samly-bug-screenshots').upload(screenshotPath,capture.blob,{contentType:capture.type,upsert:false});if(uploadError)throw uploadError;}const{error}=await supabase.rpc('submit_samly_bug_report',{p_title:title,p_description:description,p_page_path:window.location.pathname,p_screenshot_path:screenshotPath||null});if(error)throw error;setTitle('');setDescription('');setOpen(false);setMessage('Thanks — the bug report is in Uncle Samly’s repair queue.');}catch(error){setMessage(error instanceof Error?error.message:'The bug report could not be sent.');}finally{setBusy(false);}};
  if(!ready||!enabled)return null;
  return <><button type="button" aria-label="Report a bug" title="Report a bug" onClick={()=>void openReport()} disabled={capturing} className="fixed bottom-20 right-4 z-30 inline-flex h-11 w-11 items-center justify-center rounded-full bg-slate-900 text-white shadow-lg transition hover:bg-blue-700 disabled:opacity-70 lg:bottom-5"><Bug className="h-5 w-5"/></button>{message&&!open&&<p className="fixed bottom-20 right-16 z-30 max-w-xs rounded-lg bg-slate-900 px-3 py-2 text-sm text-white shadow-lg lg:bottom-5">{message}</p>}<Modal isOpen={open} onClose={()=>setOpen(false)} title="Report a bug"><form onSubmit={submit} className="space-y-4"><p className="text-sm text-slate-600">Tell us what went wrong. We captured the page behind this window to help reproduce it{capture?' and will attach it privately for Samly support.':'.'} </p><Input label="Short title" value={title} minLength={4} maxLength={160} onChange={e=>setTitle(e.target.value)} required/><div><label className="mb-1 block text-sm font-medium text-gray-700">What happened?</label><textarea value={description} minLength={10} maxLength={5000} onChange={e=>setDescription(e.target.value)} required className="min-h-32 w-full rounded-lg border border-gray-300 px-3 py-2" placeholder="What did you expect, and what happened instead?"/></div>{message&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Sending…':'Send bug report'}</Button></div></form></Modal></>;
}
