-- Private staging for the 2025 FreeFinance journal, invoices, and assets.
begin;
create table if not exists public.freefinance_import_batches(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id)on delete cascade,source_file text not null,source_kind text not null check(source_kind in('journal','invoices','assets','depreciation')),source_row_count integer not null,source_sha256 text not null,status text not null default 'staged' check(status in('staged','validated','imported','rejected')),control_totals jsonb not null default '{}',created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(workspace_id,source_sha256));
create table if not exists public.freefinance_journal_staging(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.freefinance_import_batches(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,source_row integer not null,booking_number text,booking_date_text text,account_text text,contra_account_text text,invoice_number text,reference text,description text,internal_note text,counterparty text,uva_period text,tax_rate_text text,ust_info text,net_text text,tax_text text,gross_text text,validation_errors text[] not null default '{}',unique(batch_id,source_row));
create table if not exists public.freefinance_invoice_staging(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.freefinance_import_batches(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,source_row integer not null,source_number text,counterparty text,invoice_date_text text,due_date_text text,paid_date_text text,invoice_number text,currency text,foreign_currency_text text,net_text text,tax_text text,gross_text text,open_text text,validation_errors text[] not null default '{}',unique(batch_id,source_row));
create table if not exists public.freefinance_asset_staging(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.freefinance_import_batches(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,source_row integer not null,asset_number text,asset_type text,depreciation_method text,description text,supplier text,acquisition_date_text text,acquisition_cost_text text,original_cost_text text,useful_life_text text,book_value_text text,next_depreciation_text text,disposed_date_text text,validation_errors text[] not null default '{}',unique(batch_id,source_row));
do $$declare t text;begin foreach t in array array['freefinance_import_batches','freefinance_journal_staging','freefinance_invoice_staging','freefinance_asset_staging']loop execute format('alter table public.%I enable row level security',t);execute format('drop policy if exists %I on public.%I',t||'_read',t);execute format('drop policy if exists %I on public.%I',t||'_write',t);execute format('create policy %I on public.%I for select to authenticated using(public.is_workspace_member(workspace_id))',t||'_read',t);execute format('create policy %I on public.%I for all to authenticated using(public.can_admin(workspace_id))with check(public.can_admin(workspace_id))',t||'_write',t);end loop;end$$;
commit;
select table_name from information_schema.tables where table_schema='public' and table_name like 'freefinance%staging' or table_schema='public' and table_name='freefinance_import_batches' order by table_name;
