-- Reconciliation-only staging for Austrian QuickBooks exports. FreeFinance
-- remains the bookkeeping source of truth; these rows must not create ledger entries.
begin;
create table if not exists public.quickbooks_reconciliation_batches(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id)on delete cascade,source_file text not null,source_kind text not null check(source_kind in('customers','suppliers','invoices','general_ledger','trial_balance')),source_row_count integer not null,source_sha256 text not null,status text not null default 'staged' check(status in('staged','reconciled','rejected')),created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(workspace_id,source_sha256));
create table if not exists public.quickbooks_reconciliation_rows(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.quickbooks_reconciliation_batches(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,source_row integer not null,external_id text,record_type text,record_date text,document_number text,name text,email text,currency text,amount_text text,open_amount_text text,raw_data jsonb not null default '{}',matched_entity_type text,matched_entity_id uuid,reconciliation_status text not null default 'unmatched' check(reconciliation_status in('unmatched','matched','difference','ignored')),notes text,unique(batch_id,source_row));
alter table public.quickbooks_reconciliation_batches enable row level security;alter table public.quickbooks_reconciliation_rows enable row level security;
drop policy if exists quickbooks_reconciliation_batches_read on public.quickbooks_reconciliation_batches;drop policy if exists quickbooks_reconciliation_batches_write on public.quickbooks_reconciliation_batches;create policy quickbooks_reconciliation_batches_read on public.quickbooks_reconciliation_batches for select to authenticated using(public.is_workspace_member(workspace_id));create policy quickbooks_reconciliation_batches_write on public.quickbooks_reconciliation_batches for all to authenticated using(public.can_admin(workspace_id))with check(public.can_admin(workspace_id));
drop policy if exists quickbooks_reconciliation_rows_read on public.quickbooks_reconciliation_rows;drop policy if exists quickbooks_reconciliation_rows_write on public.quickbooks_reconciliation_rows;create policy quickbooks_reconciliation_rows_read on public.quickbooks_reconciliation_rows for select to authenticated using(public.is_workspace_member(workspace_id));create policy quickbooks_reconciliation_rows_write on public.quickbooks_reconciliation_rows for all to authenticated using(public.can_admin(workspace_id))with check(public.can_admin(workspace_id));
commit;
select table_name from information_schema.tables where table_schema='public'and table_name like 'quickbooks_reconciliation%'order by table_name;
