-- Austrian GWG/AfA decisions and annual depreciation schedule.
begin;
alter table public.fixed_assets add column if not exists placed_in_service_date date,add column if not exists vat_recoverable boolean not null default true,add column if not exists gwg_elected boolean not null default false,add column if not exists depreciation_rate numeric(9,6),add column if not exists status text not null default 'active' check(status in('draft','active','disposed','fully_depreciated'));
create table if not exists public.fixed_asset_depreciation_schedule(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id)on delete cascade,asset_id uuid not null references public.fixed_assets(id)on delete cascade,fiscal_year integer not null,opening_book_value numeric(15,2)not null,depreciation_amount numeric(15,2)not null,closing_book_value numeric(15,2)not null,half_year_rule_applied boolean not null default false,status text not null default 'planned' check(status in('planned','posted','cancelled')),transaction_id uuid references public.transactions(id),unique(asset_id,fiscal_year));
alter table public.fixed_asset_depreciation_schedule enable row level security;drop policy if exists fixed_asset_depreciation_schedule_read on public.fixed_asset_depreciation_schedule;drop policy if exists fixed_asset_depreciation_schedule_write on public.fixed_asset_depreciation_schedule;create policy fixed_asset_depreciation_schedule_read on public.fixed_asset_depreciation_schedule for select to authenticated using(public.is_workspace_member(workspace_id));create policy fixed_asset_depreciation_schedule_write on public.fixed_asset_depreciation_schedule for all to authenticated using(public.can_write(workspace_id))with check(public.can_write(workspace_id));
commit;

create or replace function public.create_austrian_asset(p_workspace_id uuid,p_account_id uuid,p_description text,p_supplier text,p_acquisition_date date,p_placed_in_service_date date,p_cost numeric,p_vat_recoverable boolean,p_method text,p_useful_life numeric,p_degressive_rate numeric default null,p_elect_gwg boolean default false)
returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v_gwg_limit numeric:=1000;v_base numeric;v_year int;v_open numeric;v_dep numeric;v_half boolean;begin
if not public.can_write(p_workspace_id)or not exists(select 1 from public.workspaces where id=p_workspace_id and country='AT')then raise exception 'Not authorized Austrian workspace';end if;if p_cost<=0 then raise exception 'Cost must be positive';end if;
if p_elect_gwg and p_cost>v_gwg_limit then raise exception 'GWG election exceeds EUR 1,000 threshold';end if;if not p_elect_gwg and(coalesce(p_useful_life,0)<=0)then raise exception 'Useful life required';end if;if p_method not in('linear','degressive','gwg_immediate')then raise exception 'Invalid method';end if;if p_method='degressive'and(p_degressive_rate<=0 or p_degressive_rate>.30)then raise exception 'Degressive rate must be at most 30%%';end if;
insert into public.fixed_assets(workspace_id,account_id,description,supplier,acquisition_date,placed_in_service_date,acquisition_cost,original_cost,useful_life_years,book_value,depreciation_method,depreciation_rate,vat_recoverable,gwg_elected,status)
values(p_workspace_id,p_account_id,p_description,p_supplier,p_acquisition_date,p_placed_in_service_date,p_cost,p_cost,p_useful_life,case when p_elect_gwg then 0 else p_cost end,case when p_elect_gwg then 'gwg_immediate'else p_method end,p_degressive_rate,p_vat_recoverable,p_elect_gwg,case when p_elect_gwg then 'fully_depreciated'else'active'end)returning id into v_id;
if not p_elect_gwg then v_base:=p_cost;v_open:=p_cost;for v_year in extract(year from p_placed_in_service_date)::int..extract(year from p_placed_in_service_date)::int+ceil(p_useful_life)::int loop exit when v_open<=0;v_half:=v_year=extract(year from p_placed_in_service_date)::int and extract(month from p_placed_in_service_date)>6;v_dep:=case when p_method='linear'then round(v_base/p_useful_life,2)else round(v_open*p_degressive_rate,2)end;if v_half then v_dep:=round(v_dep/2,2);end if;v_dep:=least(v_dep,v_open);insert into public.fixed_asset_depreciation_schedule(workspace_id,asset_id,fiscal_year,opening_book_value,depreciation_amount,closing_book_value,half_year_rule_applied)values(p_workspace_id,v_id,v_year,v_open,v_dep,v_open-v_dep);v_open:=v_open-v_dep;end loop;end if;return v_id;end$$;
revoke all on function public.create_austrian_asset(uuid,uuid,text,text,date,date,numeric,boolean,text,numeric,numeric,boolean)from public;grant execute on function public.create_austrian_asset(uuid,uuid,text,text,date,date,numeric,boolean,text,numeric,numeric,boolean)to authenticated;
