-- Human-approved statement extraction. Original files remain evidence; parsed
-- rows cannot become bank transactions until the statement reconciles.
begin;
create table if not exists public.bank_statement_imports(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id)on delete cascade,bank_account_id uuid references public.bank_accounts(id),account_role text not null check(account_role in('bank','credit_card','clearing')),institution_name text not null,statement_from date,statement_to date,opening_balance numeric(15,2),closing_balance numeric(15,2),currency text not null,file_name text not null,file_path text,file_sha256 text not null,extraction_method text not null default 'pending' check(extraction_method in('pending','csv','pdf_text','ocr_ai','manual')),status text not null default 'uploaded' check(status in('uploaded','extracted','needs_review','reconciled','imported','rejected')),extraction_error text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(workspace_id,file_sha256));
create table if not exists public.bank_statement_rows(id uuid primary key default gen_random_uuid(),statement_import_id uuid not null references public.bank_statement_imports(id)on delete cascade,workspace_id uuid not null references public.workspaces(id)on delete cascade,source_page integer,source_line text,row_order integer not null,booked_date date,value_date date,description text,counterparty text,reference text,amount numeric(15,2),currency text,confidence numeric(5,4),review_status text not null default 'proposed' check(review_status in('proposed','approved','corrected','ignored')),classification text check(classification in('business','private','internal_transfer','card_settlement','unknown')),suggested_account_id uuid references public.accounts(id),approved_by uuid references auth.users(id),approved_at timestamptz,unique(statement_import_id,row_order));
do $$declare t text;begin foreach t in array array['bank_statement_imports','bank_statement_rows']loop execute format('alter table public.%I enable row level security',t);execute format('drop policy if exists %I on public.%I',t||'_read',t);execute format('drop policy if exists %I on public.%I',t||'_write',t);execute format('create policy %I on public.%I for select to authenticated using(public.is_workspace_member(workspace_id))',t||'_read',t);execute format('create policy %I on public.%I for all to authenticated using(public.can_write(workspace_id))with check(public.can_write(workspace_id))',t||'_write',t);end loop;end$$;
do $$declare v_ws uuid:='d621017c-e9bd-4334-a07f-5e7b6d31ef6e';begin
insert into public.bank_accounts(workspace_id,account_id,bank_name,currency,is_active)
select v_ws,a.id,'Bank Austria','EUR',true from public.accounts a where a.workspace_id=v_ws and a.code='2800'and not exists(select 1 from public.bank_accounts where workspace_id=v_ws and bank_name='Bank Austria');
insert into public.bank_accounts(workspace_id,account_id,bank_name,currency,is_active)
select v_ws,a.id,'N26 (credit card / clearing)','EUR',true from public.accounts a where a.workspace_id=v_ws and a.code='2790'and not exists(select 1 from public.bank_accounts where workspace_id=v_ws and bank_name='N26 (credit card / clearing)');
end$$;
commit;
create or replace function public.reconcile_bank_statement(p_import_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare s public.bank_statement_imports%rowtype;v_sum numeric;v_unreviewed int;v_delta numeric;begin select*into s from public.bank_statement_imports where id=p_import_id for update;if not found or not public.can_write(s.workspace_id)then raise exception 'Statement not found or unauthorized';end if;select coalesce(sum(amount),0),count(*)filter(where review_status='proposed'or amount is null or booked_date is null)into v_sum,v_unreviewed from public.bank_statement_rows where statement_import_id=p_import_id;v_delta:=round(coalesce(s.opening_balance,0)+v_sum-coalesce(s.closing_balance,0),2);if s.opening_balance is null or s.closing_balance is null or v_unreviewed>0 or v_delta<>0 then update public.bank_statement_imports set status='needs_review'where id=p_import_id;else update public.bank_statement_imports set status='reconciled'where id=p_import_id;end if;return jsonb_build_object('movement_total',v_sum,'balance_delta',v_delta,'unreviewed_rows',v_unreviewed,'reconciled',v_delta=0 and v_unreviewed=0);end$$;
revoke all on function public.reconcile_bank_statement(uuid)from public;grant execute on function public.reconcile_bank_statement(uuid)to authenticated;
